In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)

sns.set_theme(style="whitegrid")

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# ==============================
# VERSION CHECK
# ==============================

print("Python environment is ready.")
print("Pandas version   :", pd.__version__)
print("NumPy version    :", np.__version__)
print("Matplotlib version:", plt.matplotlib.__version__)
print("Seaborn version  :", sns.__version__)

Python environment is ready.
Pandas version   : 3.0.5
NumPy version    : 2.5.1
Matplotlib version: 3.11.1
Seaborn version  : 0.13.2

In [4]:
# ==============================
# PROJECT PATHS
# ==============================

PROJECT_ROOT = Path("..")

RAW_DATA = PROJECT_ROOT / "data" / "raw"
RAW_2024 = RAW_DATA / "election_2024"
RAW_HISTORICAL = RAW_DATA / "historical"

PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"

print("Project root      :", PROJECT_ROOT.resolve())
print("2024 data folder  :", RAW_2024.resolve())
print("Processed folder  :", PROCESSED_DATA.resolve())

Project root      : C:\Users\mural\Indian_Election_Analysis
2024 data folder  : C:\Users\mural\Indian_Election_Analysis\data\raw\election_2024
Processed folder  : C:\Users\mural\Indian_Election_Analysis\data\processed

In [5]:
# ==============================
# CHECK PROJECT DIRECTORIES
# ==============================

folders = {
    "Raw Data": RAW_DATA,
    "2024 Data": RAW_2024,
    "Historical Data": RAW_HISTORICAL,
    "Processed Data": PROCESSED_DATA
}

for name, path in folders.items():
    print(f"{name:<20} : {'FOUND' if path.exists() else 'NOT FOUND'}")

Raw Data             : FOUND
2024 Data            : FOUND
Historical Data      : FOUND
Processed Data       : FOUND

In [6]:
# ==============================
# CHECK AVAILABLE 2024 FILES
# ==============================

if RAW_2024.exists():
    files = list(RAW_2024.iterdir())

    if files:
        print("Files available in election_2024:")
        for file in files:
            print(" -", file.name)
    else:
        print("The election_2024 folder is empty.")
else:
    print("The election_2024 folder does not exist.")

Files available in election_2024:
 - candidates_with_phase.csv
 - results_2024.csv
 - results_2024_winners.csv

In [7]:
# ============================================
# MODULE 2: LOAD 2024 LOK SABHA DATA
# ============================================

candidates_path = RAW_2024 / "candidates_with_phase.csv"
results_path = RAW_2024 / "results_2024.csv"
winners_path = RAW_2024 / "results_2024_winners.csv"

print("File paths created successfully.")

File paths created successfully.

In [8]:
# ============================================
# LOAD DATASETS
# ============================================

candidates_df = pd.read_csv(candidates_path)
results_df = pd.read_csv(results_path)
winners_df = pd.read_csv(winners_path)

print("All 2024 Lok Sabha datasets loaded successfully.")

All 2024 Lok Sabha datasets loaded successfully.

In [9]:
# ============================================
# DATASET DIMENSIONS
# ============================================

print("Candidates Dataset")
print("------------------")
print("Rows    :", candidates_df.shape[0])
print("Columns :", candidates_df.shape[1])

print("\nResults Dataset")
print("----------------")
print("Rows    :", results_df.shape[0])
print("Columns :", results_df.shape[1])

print("\nWinners Dataset")
print("----------------")
print("Rows    :", winners_df.shape[0])
print("Columns :", winners_df.shape[1])

Candidates Dataset
------------------
Rows    : 8441
Columns : 14

Results Dataset
----------------
Rows    : 8902
Columns : 10

Winners Dataset
----------------
Rows    : 543
Columns : 9

In [10]:
# ============================================
# PREVIEW DATA
# ============================================

print("CANDIDATES DATA")
display(candidates_df.head())

print("\nRESULTS DATA")
display(results_df.head())

print("\nWINNERS DATA")
display(winners_df.head())

CANDIDATES DATA

,State,Constituency_No,Constituency,Party,Candidate Name,Gender,Age,Address,Application Date,Application Status,Father/Husband's Name,Photo Link,Phase,Polling Date
0,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,V.K. ABDUL AZIZ,male,42,Brindaban,"27th March, 2024",Accepted,V.M. KOCHUNNI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
1,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,USHA KUMARI,female,39,"Dollygunj Village, Port Blair Tehsil, South An...","27th March, 2024",Accepted,S B GURUNG,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
2,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,RINKU MALA MONDAL,female,36,"Lokenath Colony, Dollygunj","27th March, 2024",Accepted,N N MONDAL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
3,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Indian National Congress,KULDEEP RAI SHARMA,male,56,"M.B.167, M.G. Road, Junglighat, Port Blair - 7...","27th March, 2024",Accepted,BHAGAT SINGH,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
4,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,ANAND RAMNATH ARLEKAR,male,58,"Panipath Road, Haddo","27th March, 2024",Accepted,RAMNATH ARLEKAR,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024

RESULTS DATA

,State,PC No,PC Name,Sl no,Candidate,Party,EVM Votes,Postal Votes,Total Votes,Vote Share
0,Andhra Pradesh,1,Araku (ST),1,GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,471470,5535,477005,40.96
1,Andhra Pradesh,1,Araku (ST),2,KOTHAPALLI GEETHA,Bharatiya Janata Party,417113,9312,426425,36.62
2,Andhra Pradesh,1,Araku (ST),3,APPALANARASA PACHIPENTA,Communist Party of India (Marxist),119016,4113,123129,10.57
3,Andhra Pradesh,1,Araku (ST),4,AVASHYA LAHARI . VARAM,Bahujan Samaj Party,24858,892,25750,2.21
4,Andhra Pradesh,1,Araku (ST),5,SAMAREDDY BALAKRISHNA,Independent,9493,42,9535,0.82

WINNERS DATA

,State,PC No,PC Name,Winning Candidate,Winning Party,Runner-up Canddiate,Runner-up Party,Margin Votes,Results Status
0,Andhra Pradesh,7,Amalapuram (SC),G M HARISH (BALAYOGI),Telugu Desam,RAPAKA VARAPRASADA RAO,Yuvajana Sramika Rythu Congress Party,342196,Result Declared
1,Andhra Pradesh,5,Anakapalle,C.M.RAMESH,Bharatiya Janata Party,BUDI MUTYALA NAIDU,Yuvajana Sramika Rythu Congress Party,296530,Result Declared
2,Andhra Pradesh,19,Ananthapur,AMBICA G LAKSHMINARAYANA VALMIKI,Telugu Desam,MALAGUNDLA SANKAR NARAYANA,Yuvajana Sramika Rythu Congress Party,188555,Result Declared
3,Andhra Pradesh,1,Araku (ST),GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,KOTHAPALLI GEETHA,Bharatiya Janata Party,50580,Result Declared
4,Andhra Pradesh,15,Bapatla (SC),KRISHNA PRASAD TENNETI,Telugu Desam,NANDIGAM SURESH BABU,Yuvajana Sramika Rythu Congress Party,208031,Result Declared

In [11]:
# ============================================
# COLUMN INFORMATION
# ============================================

print("Candidates Columns:")
print(candidates_df.columns.tolist())

print("\nResults Columns:")
print(results_df.columns.tolist())

print("\nWinners Columns:")
print(winners_df.columns.tolist())

Candidates Columns:
['State', 'Constituency_No', 'Constituency', 'Party', 'Candidate Name', 'Gender', 'Age', 'Address', 'Application Date', 'Application Status', "Father/Husband's Name", 'Photo Link', 'Phase', 'Polling Date']

Results Columns:
['State', 'PC No', 'PC Name', 'Sl no', 'Candidate', 'Party', 'EVM Votes', 'Postal Votes', 'Total Votes', 'Vote Share']

Winners Columns:
['State', 'PC No', 'PC Name', 'Winning Candidate', 'Winning Party', 'Runner-up Canddiate', 'Runner-up Party', 'Margin Votes', 'Results Status']

In [12]:
# ============================================
# DATA TYPES
# ============================================

print("CANDIDATES DATA TYPES")
print("=====================")
candidates_df.info()

print("\n\nRESULTS DATA TYPES")
print("==================")
results_df.info()

print("\n\nWINNERS DATA TYPES")
print("==================")
winners_df.info()

CANDIDATES DATA TYPES
=====================
<class 'pandas.DataFrame'>
RangeIndex: 8441 entries, 0 to 8440
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   State                  8441 non-null   str
 1   Constituency_No        8441 non-null   int64
 2   Constituency           8441 non-null   str
 3   Party                  8441 non-null   str
 4   Candidate Name         8441 non-null   str
 5   Gender                 8441 non-null   str
 6   Age                    8441 non-null   int64
 7   Address                8441 non-null   str
 8   Application Date       8441 non-null   str
 9   Application Status     8441 non-null   str
 10  Father/Husband's Name  8441 non-null   str
 11  Photo Link             8441 non-null   str
 12  Phase                  8441 non-null   int64
 13  Polling Date           8441 non-null   str
dtypes: int64(3), str(11)
memory usage: 923.4 KB


RESULTS DATA TYPES
==================
<class 'pandas.DataFrame'>
RangeIndex: 8902 entries, 0 to 8901
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   State         8902 non-null   str
 1   PC No         8902 non-null   int64
 2   PC Name       8902 non-null   str
 3   Sl no         8902 non-null   int64
 4   Candidate     8902 non-null   str
 5   Party         8902 non-null   str
 6   EVM Votes     8902 non-null   str
 7   Postal Votes  8902 non-null   str
 8   Total Votes   8902 non-null   str
 9   Vote Share    8902 non-null   str
dtypes: int64(2), str(8)
memory usage: 695.6 KB


WINNERS DATA TYPES
==================
<class 'pandas.DataFrame'>
RangeIndex: 543 entries, 0 to 542
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State                543 non-null    str
 1   PC No                543 non-null    int64
 2   PC Name              543 non-null    str
 3   Winning Candidate    543 non-null    str
 4   Winning Party        543 non-null    str
 5   Runner-up Canddiate  542 non-null    str
 6   Runner-up Party      542 non-null    str
 7   Margin Votes         543 non-null    str
 8   Results Status       543 non-null    str
dtypes: int64(1), str(8)
memory usage: 38.3 KB

In [13]:
# ============================================
# MISSING VALUES
# ============================================

print("Candidates Missing Values")
print("=========================")
display(candidates_df.isnull().sum())

print("\nResults Missing Values")
print("======================")
display(results_df.isnull().sum())

print("\nWinners Missing Values")
print("=======================")
display(winners_df.isnull().sum())

Candidates Missing Values
=========================

State                    0
Constituency_No          0
Constituency             0
Party                    0
Candidate Name           0
Gender                   0
Age                      0
Address                  0
Application Date         0
Application Status       0
Father/Husband's Name    0
Photo Link               0
Phase                    0
Polling Date             0
dtype: int64

Results Missing Values
======================

State           0
PC No           0
PC Name         0
Sl no           0
Candidate       0
Party           0
EVM Votes       0
Postal Votes    0
Total Votes     0
Vote Share      0
dtype: int64

Winners Missing Values
=======================

State                  0
PC No                  0
PC Name                0
Winning Candidate      0
Winning Party          0
Runner-up Canddiate    1
Runner-up Party        1
Margin Votes           0
Results Status         0
dtype: int64

In [14]:
# ============================================
# DUPLICATE RECORDS
# ============================================

print("Candidates duplicate rows :", candidates_df.duplicated().sum())
print("Results duplicate rows    :", results_df.duplicated().sum())
print("Winners duplicate rows    :", winners_df.duplicated().sum())

Candidates duplicate rows : 0
Results duplicate rows    : 0
Winners duplicate rows    : 0

In [15]:
# ============================================
# UNIQUE STATES
# ============================================

print("Number of states:", candidates_df["State"].nunique())

print("\nStates:")
print(sorted(candidates_df["State"].dropna().unique()))

Number of states: 36

States:
['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli and Daman & Diu', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'NCT OF Delhi', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [16]:
print("Election Years:")

Election Years:

In [17]:
# ============================================
# VERIFY DATASET YEAR
# ============================================

print("This dataset is the 2024 Lok Sabha dataset.")
print("Year column is not required because the source dataset is already specific to 2024.")

This dataset is the 2024 Lok Sabha dataset.
Year column is not required because the source dataset is already specific to 2024.

In [18]:
# ============================================
# MODULE 3: COLUMN INSPECTION
# ============================================

datasets = {
    "Candidates": candidates_df,
    "Results": results_df,
    "Winners": winners_df
}

for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(f"{name} Dataset")
    print(f"{'=' * 50}")
    
    print("Shape:", df.shape)
    print("Columns:")
    
    for i, column in enumerate(df.columns, start=1):
        print(f"{i}. {column}")

==================================================
Candidates Dataset
==================================================
Shape: (8441, 14)
Columns:
1. State
2. Constituency_No
3. Constituency
4. Party
5. Candidate Name
6. Gender
7. Age
8. Address
9. Application Date
10. Application Status
11. Father/Husband's Name
12. Photo Link
13. Phase
14. Polling Date

==================================================
Results Dataset
==================================================
Shape: (8902, 10)
Columns:
1. State
2. PC No
3. PC Name
4. Sl no
5. Candidate
6. Party
7. EVM Votes
8. Postal Votes
9. Total Votes
10. Vote Share

==================================================
Winners Dataset
==================================================
Shape: (543, 9)
Columns:
1. State
2. PC No
3. PC Name
4. Winning Candidate
5. Winning Party
6. Runner-up Canddiate
7. Runner-up Party
8. Margin Votes
9. Results Status

In [19]:
# ============================================
# SAMPLE RECORDS
# ============================================

for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(f"{name} Dataset - First 3 Rows")
    print(f"{'=' * 50}")
    
    display(df.head(3))

==================================================
Candidates Dataset - First 3 Rows
==================================================

,State,Constituency_No,Constituency,Party,Candidate Name,Gender,Age,Address,Application Date,Application Status,Father/Husband's Name,Photo Link,Phase,Polling Date
0,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,V.K. ABDUL AZIZ,male,42,Brindaban,"27th March, 2024",Accepted,V.M. KOCHUNNI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
1,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,USHA KUMARI,female,39,"Dollygunj Village, Port Blair Tehsil, South An...","27th March, 2024",Accepted,S B GURUNG,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
2,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,RINKU MALA MONDAL,female,36,"Lokenath Colony, Dollygunj","27th March, 2024",Accepted,N N MONDAL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024

==================================================
Results Dataset - First 3 Rows
==================================================

,State,PC No,PC Name,Sl no,Candidate,Party,EVM Votes,Postal Votes,Total Votes,Vote Share
0,Andhra Pradesh,1,Araku (ST),1,GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,471470,5535,477005,40.96
1,Andhra Pradesh,1,Araku (ST),2,KOTHAPALLI GEETHA,Bharatiya Janata Party,417113,9312,426425,36.62
2,Andhra Pradesh,1,Araku (ST),3,APPALANARASA PACHIPENTA,Communist Party of India (Marxist),119016,4113,123129,10.57

==================================================
Winners Dataset - First 3 Rows
==================================================

,State,PC No,PC Name,Winning Candidate,Winning Party,Runner-up Canddiate,Runner-up Party,Margin Votes,Results Status
0,Andhra Pradesh,7,Amalapuram (SC),G M HARISH (BALAYOGI),Telugu Desam,RAPAKA VARAPRASADA RAO,Yuvajana Sramika Rythu Congress Party,342196,Result Declared
1,Andhra Pradesh,5,Anakapalle,C.M.RAMESH,Bharatiya Janata Party,BUDI MUTYALA NAIDU,Yuvajana Sramika Rythu Congress Party,296530,Result Declared
2,Andhra Pradesh,19,Ananthapur,AMBICA G LAKSHMINARAYANA VALMIKI,Telugu Desam,MALAGUNDLA SANKAR NARAYANA,Yuvajana Sramika Rythu Congress Party,188555,Result Declared

In [20]:
# ============================================
# CATEGORICAL DATA INSPECTION
# ============================================

for name, df in datasets.items():
    print(f"\n{'=' * 50}")
    print(f"{name} Dataset")
    print(f"{'=' * 50}")
    
    categorical_columns = df.select_dtypes(include=["object", "string"]).columns
    
    for column in categorical_columns:
        print(f"\n{column}")
        print("Unique values:", df[column].nunique())
        print(df[column].dropna().unique()[:10])

==================================================
Candidates Dataset
==================================================

State
Unique values: 36
<StringArray>
[           'Andaman & Nicobar Islands',                       'Andhra Pradesh',
                    'Arunachal Pradesh',                                'Assam',
                                'Bihar',                           'Chandigarh',
                         'Chhattisgarh', 'Dadra & Nagar Haveli and Daman & Diu',
                                  'Goa',                              'Gujarat']
Length: 10, dtype: str

Constituency
Unique values: 541
<StringArray>
['Andaman & Nicobar Islands',                'Araku (ST)',                'Srikakulam',              'Vizianagaram',
             'Visakhapatnam',                'Anakapalle',                  'Kakinada',           'Amalapuram (SC)',
               'Rajahmundry',                'Narsapuram']
Length: 10, dtype: str

Party
Unique values: 749
<StringArray>
[                                'Independent',                    'Indian National Congress',
 'Socialist Unity Centre Of India (COMMUNIST)',    'All India Anna Dravida Munnetra Kazhagam',
         'Andaman Nicobar Democratic Congress',         'Communist Party of India  (Marxist)',
                         'Bahujan Samaj Party',                      'Bharatiya Janata Party',
                        'Bharat Adivasi Party',                    'India Praja Bandhu Party']
Length: 10, dtype: str

Candidate Name
Unique values: 8105

<StringArray>
[      'V.K. ABDUL AZIZ',           'USHA KUMARI',     'RINKU MALA MONDAL',    'KULDEEP RAI SHARMA',
 'ANAND RAMNATH ARLEKAR',     'K VENKAT RAM BABU',        'SALAMAT MONDAL',        'K J B SELVARAJ',
            'MANOJ PAUL',            'D AYYAPPAN']
Length: 10, dtype: str

Gender
Unique values: 3
<StringArray>
['male', 'female', 'third']
Length: 3, dtype: str

Address
Unique values: 8360
<StringArray>
[                                                         'Brindaban',
       'Dollygunj Village, Port Blair Tehsil, South Andaman District',
                                         'Lokenath Colony, Dollygunj',
                'M.B.167, M.G. Road, Junglighat, Port Blair - 744103',
                                               'Panipath Road, Haddo',
                                                       'Wimberlygunj',
     'Garacharma-II, Bathu Basti, Port Blair, South Andaman - 744105',
 'ALAN HOUSE, NEAR SONY TILES GODOWN, DOLLYGUNJ, PORT BLAIR - 744103',
       'MADHUPUR-1, DIGLIPUR, NORTH ANDAMAN, A AND N ISLANDS, 744202',
             'FLAT NO. 32, G BLOCK D AND K CITY, PORT BLAIR - 744103']
Length: 10, dtype: str

Application Date
Unique values: 40
<StringArray>
['27th March, 2024', '26th March, 2024', '22nd March, 2024', '22nd April, 2024', '24th April, 2024',
 '25th April, 2024', '19th April, 2024', '23rd April, 2024', '18th April, 2024', '20th April, 2024']
Length: 10, dtype: str

Application Status
Unique values: 1
<StringArray>
['Accepted']
Length: 1, dtype: str

Father/Husband's Name
Unique values: 7835
<StringArray>
[     'V.M. KOCHUNNI',         'S B GURUNG',         'N N MONDAL',       'BHAGAT SINGH',    'RAMNATH ARLEKAR',
        'K THATHAYYA',           'YEAD ALI',    'G KULANDAI SAMY', 'NIRODE BIHARI PAUL',        'P DAMODARAN']
Length: 10, dtype: str

Photo Link
Unique values: 8367
<StringArray>
[  'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/VKA-2024-2102.jpg',
 'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/USHAK-2024-2088.jpg',
 'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/RINKU-2024-2056.jpg',
 'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/KULDE-2024-2038.jpg',
 'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/ANAND-2024-2008.jpg',
 'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/KVENK-2024-1997.jpg',
 'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/SALAM-2024-1955.jpg',
  'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/KJBSE-2024-986.jpg',
  'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/MANOJ-2024-970.jpg',
  'https://results.eci.gov.in/uploads4/candprofile/2024/PC/E24/U01/DAYYA-2024-944.jpg']
Length: 10, dtype: str

Polling Date
Unique values: 9
<StringArray>
['19-04-2024', '13-05-2024', '07-05-2024', '26-04-2024', '25-05-2024', '20-05-2024', '01-06-2024',  '07-May-24',
  '01-Jun-24']
Length: 9, dtype: str

==================================================
Results Dataset
==================================================

State
Unique values: 36
<StringArray>
[   'Andhra Pradesh', 'Arunachal Pradesh',             'Assam',             'Bihar',               'Goa',
           'Gujarat',           'Haryana',  'Himachal Pradesh',         'Karnataka',            'Kerala']
Length: 10, dtype: str

PC Name
Unique values: 541
<StringArray>
[     'Araku (ST)',      'Srikakulam',    'Vizianagaram',   'Visakhapatnam',      'Anakapalle',        'Kakinada',
 'Amalapuram (SC)',     'Rajahmundry',      'Narsapuram',           'Eluru']
Length: 10, dtype: str

Candidate
Unique values: 8101
<StringArray>
[     'GUMMA THANUJA RANI',       'KOTHAPALLI GEETHA', 'APPALANARASA PACHIPENTA',  'AVASHYA LAHARI . VARAM',
   'SAMAREDDY BALAKRISHNA',        'NIMMAKA JAYARAJU',                 'ATHIDHI',         'CHANTI BADNAINA',
     'MOTTADAM . RAJABABU',    'RANJITH KUMAR PALAKA']
Length: 10, dtype: str

Party
Unique values: 746
<StringArray>
['Yuvajana Sramika Rythu Congress Party',                'Bharatiya Janata Party',
   'Communist Party of India  (Marxist)',                   'Bahujan Samaj Party',
                           'Independent',             'Jai Bharat National Party',
                  'Bharat Adivasi Party',       'Telugu Rajadhikara Samiti Party',
              'India Praja Bandhu Party',                     'None of the Above']
Length: 10, dtype: str

EVM Votes
Unique values: 6081
<StringArray>
['471470', '417113', '119016', '24858', '9493', '8798', '8121', '7205', '6370', '6000']
Length: 10, dtype: str

Postal Votes
Unique values: 1447
<StringArray>
['5535', '9312', '4113', '892', '42', '664', '15', '47', '396', '26']
Length: 10, dtype: str

Total Votes
Unique values: 6100
<StringArray>
['477005', '426425', '123129', '25750', '9535', '9462', '8136', '7252', '6766', '6047']
Length: 10, dtype: str

Vote Share
Unique values: 1557
<StringArray>
['40.96', '36.62', '10.57', '2.21', '0.82', '0.81', '0.7', '0.62', '0.58', '0.52']
Length: 10, dtype: str

==================================================
Winners Dataset
==================================================

State
Unique values: 36
<StringArray>
[   'Andhra Pradesh', 'Arunachal Pradesh',             'Assam',             'Bihar',               'Goa',
           'Gujarat',           'Haryana',  'Himachal Pradesh',         'Karnataka',            'Kerala']
Length: 10, dtype: str

PC Name
Unique values: 541
<StringArray>
['Amalapuram (SC)',      'Anakapalle',      'Ananthapur',      'Araku (ST)',    'Bapatla (SC)',    'Chittoor(SC)',
           'Eluru',          'Guntur',        'Hindupur',          'Kadapa']
Length: 10, dtype: str

Winning Candidate
Unique values: 542
<StringArray>
[           'G M HARISH (BALAYOGI)',                       'C.M.RAMESH', 'AMBICA G LAKSHMINARAYANA VALMIKI',
               'GUMMA THANUJA RANI',           'KRISHNA PRASAD TENNETI',           'DAGGUMALLA PRASADA RAO',
               'PUTTA MAHESH KUMAR',      'DR CHANDRA SEKHAR PEMMASANI',                'B K PARTHASARATHI',
              'Y. S. AVINASH REDDY']
Length: 10, dtype: str

Winning Party
Unique values: 42
<StringArray>
[                                              'Telugu Desam',
                                     'Bharatiya Janata Party',
                      'Yuvajana Sramika Rythu Congress Party',
                                             'Janasena Party',
                                         'Asom Gana Parishad',
                                   'Indian National Congress',
                             'United People’s Party, Liberal',
 'Communist Party of India  (Marxist-Leninist)  (Liberation)',
                                       'Rashtriya Janata Dal',
                                       'Janata Dal  (United)']
Length: 10, dtype: str

Runner-up Canddiate
Unique values: 542
<StringArray>
[              'RAPAKA VARAPRASADA RAO',                   'BUDI MUTYALA NAIDU',
           'MALAGUNDLA SANKAR NARAYANA',                    'KOTHAPALLI GEETHA',
                 'NANDIGAM SURESH BABU',                         'REDDEPPA.N .',
                 'KARUMURI SUNIL KUMAR',               'KILARI VENKATA ROSAIAH',
                            'J SHANTHA', 'CHADIPIRALLA BHUPESH SUBBARAMI REDDY']
Length: 10, dtype: str

Runner-up Party
Unique values: 42
<StringArray>
['Yuvajana Sramika Rythu Congress Party',                'Bharatiya Janata Party',
                          'Telugu Desam',              'Indian National Congress',
     'All India United Democratic Front',                 'Assam Jatiya Parishad',
                           'Independent',                'Bodoland Peoples Front',
                  'Rashtriya Janata Dal',              'Communist Party of India']
Length: 10, dtype: str

Margin Votes
Unique values: 543
<StringArray>
['342196', '296530', '188555', '50580', '208031', '220479', '181857', '344695', '132427', '62695']
Length: 10, dtype: str

Results Status
Unique values: 2
<StringArray>
['Result Declared', 'Uncontested']
Length: 2, dtype: str

In [21]:
# ============================================
# MODULE 3: DATASET COMPARISON
# ============================================

print("Candidates dataset :", candidates_df.shape)
print("Results dataset    :", results_df.shape)
print("Winners dataset    :", winners_df.shape)

Candidates dataset : (8441, 14)
Results dataset    : (8902, 10)
Winners dataset    : (543, 9)

In [22]:
# ============================================
# DUPLICATE ANALYSIS
# ============================================

for name, df in datasets.items():
    print(f"{name}:")
    print("  Total rows      :", len(df))
    print("  Duplicate rows  :", df.duplicated().sum())
    print("  Unique rows     :", df.drop_duplicates().shape[0])
    print()

Candidates:
  Total rows      : 8441
  Duplicate rows  : 0
  Unique rows     : 8441

Results:
  Total rows      : 8902
  Duplicate rows  : 0
  Unique rows     : 8902

Winners:
  Total rows      : 543
  Duplicate rows  : 0
  Unique rows     : 543

In [23]:
# ============================================
# NUMERIC COLUMN INSPECTION
# ============================================

for name, df in datasets.items():
    print(f"\n{name} Dataset")
    print("-" * 40)
    
    numeric_columns = df.select_dtypes(include=np.number).columns.tolist()
    
    print("Numeric columns:")
    print(numeric_columns)

Candidates Dataset
----------------------------------------
Numeric columns:
['Constituency_No', 'Age', 'Phase']

Results Dataset
----------------------------------------
Numeric columns:
['PC No', 'Sl no']

Winners Dataset
----------------------------------------
Numeric columns:
['PC No']

In [24]:
# ============================================
# CATEGORICAL COLUMN INSPECTION
# ============================================

for name, df in datasets.items():
    print(f"\n{name} Dataset")
    print("-" * 40)
    
    categorical_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns.tolist()
    
    print("Categorical columns:")
    print(categorical_columns)

Candidates Dataset
----------------------------------------
Categorical columns:
['State', 'Constituency', 'Party', 'Candidate Name', 'Gender', 'Address', 'Application Date', 'Application Status', "Father/Husband's Name", 'Photo Link', 'Polling Date']

Results Dataset
----------------------------------------
Categorical columns:
['State', 'PC Name', 'Candidate', 'Party', 'EVM Votes', 'Postal Votes', 'Total Votes', 'Vote Share']

Winners Dataset
----------------------------------------
Categorical columns:
['State', 'PC Name', 'Winning Candidate', 'Winning Party', 'Runner-up Canddiate', 'Runner-up Party', 'Margin Votes', 'Results Status']

In [25]:
# ============================================
# UNIQUE VALUE ANALYSIS
# ============================================

for name, df in datasets.items():
    print(f"\n{'=' * 60}")
    print(name)
    print(f"{'=' * 60}")
    
    for column in df.columns:
        print(f"{column:<30} : {df[column].nunique():,} unique values")

============================================================
Candidates
============================================================
State                          : 36 unique values
Constituency_No                : 80 unique values
Constituency                   : 541 unique values
Party                          : 749 unique values
Candidate Name                 : 8,105 unique values
Gender                         : 3 unique values
Age                            : 63 unique values

Address                        : 8,360 unique values
Application Date               : 40 unique values
Application Status             : 1 unique values
Father/Husband's Name          : 7,835 unique values
Photo Link                     : 8,367 unique values
Phase                          : 7 unique values
Polling Date                   : 9 unique values

============================================================
Results
============================================================
State                          : 36 unique values
PC No                          : 80 unique values
PC Name                        : 541 unique values
Sl no                          : 55 unique values
Candidate                      : 8,101 unique values
Party                          : 746 unique values
EVM Votes                      : 6,081 unique values
Postal Votes                   : 1,447 unique values
Total Votes                    : 6,100 unique values
Vote Share                     : 1,557 unique values

============================================================
Winners
============================================================
State                          : 36 unique values
PC No                          : 80 unique values
PC Name                        : 541 unique values
Winning Candidate              : 542 unique values
Winning Party                  : 42 unique values
Runner-up Canddiate            : 542 unique values
Runner-up Party                : 42 unique values
Margin Votes                   : 543 unique values
Results Status                 : 2 unique values

In [26]:
# ============================================
# FIND CONSTITUENCY-RELATED COLUMNS
# ============================================

for name, df in datasets.items():
    print(f"\n{name} Dataset")
    
    for column in df.columns:
        if any(word in column.lower() for word in [
            "constituency",
            "const",
            "pc",
            "seat"
        ]):
            print("Possible constituency column:", column)

Candidates Dataset
Possible constituency column: Constituency_No
Possible constituency column: Constituency

Results Dataset
Possible constituency column: PC No
Possible constituency column: PC Name

Winners Dataset
Possible constituency column: PC No
Possible constituency column: PC Name

In [27]:
# ============================================
# FIND STATE-RELATED COLUMNS
# ============================================

for name, df in datasets.items():
    print(f"\n{name} Dataset")
    
    for column in df.columns:
        if any(word in column.lower() for word in [
            "state",
            "st",
            "region"
        ]):
            print("Possible state column:", column)

Candidates Dataset
Possible state column: State
Possible state column: Constituency_No
Possible state column: Constituency
Possible state column: Application Status

Results Dataset
Possible state column: State
Possible state column: Postal Votes

Winners Dataset
Possible state column: State
Possible state column: Results Status

In [28]:
# ============================================
# FIND PARTY-RELATED COLUMNS
# ============================================

for name, df in datasets.items():
    print(f"\n{name} Dataset")
    
    for column in df.columns:
        if any(word in column.lower() for word in [
            "party",
            "partyname",
            "partycode",
            "symbol"
        ]):
            print("Possible party column:", column)

Candidates Dataset
Possible party column: Party

Results Dataset
Possible party column: Party

Winners Dataset
Possible party column: Winning Party
Possible party column: Runner-up Party

In [29]:
# ============================================
# MODULE 3: FINAL COLUMN IDENTIFICATION
# ============================================

print("========== CANDIDATES ==========")
for i, col in enumerate(candidates_df.columns, 1):
    print(i, "->", col)

print("\n========== RESULTS ==========")
for i, col in enumerate(results_df.columns, 1):
    print(i, "->", col)

print("\n========== WINNERS ==========")
for i, col in enumerate(winners_df.columns, 1):
    print(i, "->", col)

========== CANDIDATES ==========
1 -> State
2 -> Constituency_No
3 -> Constituency
4 -> Party
5 -> Candidate Name
6 -> Gender
7 -> Age
8 -> Address
9 -> Application Date
10 -> Application Status
11 -> Father/Husband's Name
12 -> Photo Link
13 -> Phase
14 -> Polling Date

========== RESULTS ==========
1 -> State
2 -> PC No
3 -> PC Name
4 -> Sl no
5 -> Candidate
6 -> Party
7 -> EVM Votes
8 -> Postal Votes
9 -> Total Votes
10 -> Vote Share

========== WINNERS ==========
1 -> State
2 -> PC No
3 -> PC Name
4 -> Winning Candidate
5 -> Winning Party
6 -> Runner-up Canddiate
7 -> Runner-up Party
8 -> Margin Votes
9 -> Results Status

In [30]:
# ============================================
# SAMPLE DATA
# ============================================

display(candidates_df.head(3))
display(results_df.head(3))
display(winners_df.head(3))

,State,Constituency_No,Constituency,Party,Candidate Name,Gender,Age,Address,Application Date,Application Status,Father/Husband's Name,Photo Link,Phase,Polling Date
0,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,V.K. ABDUL AZIZ,male,42,Brindaban,"27th March, 2024",Accepted,V.M. KOCHUNNI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
1,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,USHA KUMARI,female,39,"Dollygunj Village, Port Blair Tehsil, South An...","27th March, 2024",Accepted,S B GURUNG,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
2,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,RINKU MALA MONDAL,female,36,"Lokenath Colony, Dollygunj","27th March, 2024",Accepted,N N MONDAL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024

,State,PC No,PC Name,Sl no,Candidate,Party,EVM Votes,Postal Votes,Total Votes,Vote Share
0,Andhra Pradesh,1,Araku (ST),1,GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,471470,5535,477005,40.96
1,Andhra Pradesh,1,Araku (ST),2,KOTHAPALLI GEETHA,Bharatiya Janata Party,417113,9312,426425,36.62
2,Andhra Pradesh,1,Araku (ST),3,APPALANARASA PACHIPENTA,Communist Party of India (Marxist),119016,4113,123129,10.57

,State,PC No,PC Name,Winning Candidate,Winning Party,Runner-up Canddiate,Runner-up Party,Margin Votes,Results Status
0,Andhra Pradesh,7,Amalapuram (SC),G M HARISH (BALAYOGI),Telugu Desam,RAPAKA VARAPRASADA RAO,Yuvajana Sramika Rythu Congress Party,342196,Result Declared
1,Andhra Pradesh,5,Anakapalle,C.M.RAMESH,Bharatiya Janata Party,BUDI MUTYALA NAIDU,Yuvajana Sramika Rythu Congress Party,296530,Result Declared
2,Andhra Pradesh,19,Ananthapur,AMBICA G LAKSHMINARAYANA VALMIKI,Telugu Desam,MALAGUNDLA SANKAR NARAYANA,Yuvajana Sramika Rythu Congress Party,188555,Result Declared

In [31]:
# ============================================
# MODULE 4: DATA CLEANING
# ============================================

candidates_clean = candidates_df.copy()
results_clean = results_df.copy()
winners_clean = winners_df.copy()

print("Working copies created successfully.")

Working copies created successfully.

In [32]:
# ============================================
# STANDARDIZE COLUMN NAMES
# ============================================

def clean_column_names(df):
    df = df.copy()
    
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )
    
    return df


candidates_clean = clean_column_names(candidates_clean)
results_clean = clean_column_names(results_clean)
winners_clean = clean_column_names(winners_clean)

print("Column names standardized.")

Column names standardized.

In [33]:
print("Candidates:")
print(candidates_clean.columns.tolist())

print("\nResults:")
print(results_clean.columns.tolist())

print("\nWinners:")
print(winners_clean.columns.tolist())

Candidates:
['state', 'constituency_no', 'constituency', 'party', 'candidate_name', 'gender', 'age', 'address', 'application_date', 'application_status', "father/husband's_name", 'photo_link', 'phase', 'polling_date']

Results:
['state', 'pc_no', 'pc_name', 'sl_no', 'candidate', 'party', 'evm_votes', 'postal_votes', 'total_votes', 'vote_share']

Winners:
['state', 'pc_no', 'pc_name', 'winning_candidate', 'winning_party', 'runner_up_canddiate', 'runner_up_party', 'margin_votes', 'results_status']

In [34]:
# ============================================
# REMOVE COMPLETELY EMPTY ROWS
# ============================================

candidates_clean = candidates_clean.dropna(how="all").copy()
results_clean = results_clean.dropna(how="all").copy()
winners_clean = winners_clean.dropna(how="all").copy()

print("Empty rows removed.")

Empty rows removed.

In [35]:
# ============================================
# REMOVE EXACT DUPLICATES
# ============================================

before_candidates = len(candidates_clean)
before_results = len(results_clean)
before_winners = len(winners_clean)

candidates_clean = candidates_clean.drop_duplicates().copy()
results_clean = results_clean.drop_duplicates().copy()
winners_clean = winners_clean.drop_duplicates().copy()

print("Candidates duplicates removed:", before_candidates - len(candidates_clean))
print("Results duplicates removed   :", before_results - len(results_clean))
print("Winners duplicates removed   :", before_winners - len(winners_clean))

Candidates duplicates removed: 0
Results duplicates removed   : 0
Winners duplicates removed   : 0

In [36]:
# ============================================
# CLEAN TEXT VALUES
# ============================================

def clean_text_columns(df):
    df = df.copy()
    
    text_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns
    
    for column in text_columns:
        df[column] = (
            df[column]
            .astype("string")
            .str.strip()
        )
    
    return df


candidates_clean = clean_text_columns(candidates_clean)
results_clean = clean_text_columns(results_clean)
winners_clean = clean_text_columns(winners_clean)

print("Text values cleaned.")

Text values cleaned.

In [37]:
# ============================================
# STANDARDIZE EMPTY VALUES
# ============================================

def standardize_missing_values(df):
    df = df.copy()
    
    df = df.replace({
        "": np.nan,
        "NA": np.nan,
        "N/A": np.nan,
        "null": np.nan,
        "NULL": np.nan,
        "-": np.nan
    })
    
    return df


candidates_clean = standardize_missing_values(candidates_clean)
results_clean = standardize_missing_values(results_clean)
winners_clean = standardize_missing_values(winners_clean)

print("Missing-value representation standardized.")

Missing-value representation standardized.

In [38]:
# ============================================
# CLEANING VALIDATION
# ============================================

datasets_clean = {
    "Candidates": candidates_clean,
    "Results": results_clean,
    "Winners": winners_clean
}

for name, df in datasets_clean.items():
    print(f"\n{'=' * 50}")
    print(name)
    print(f"{'=' * 50}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicates:", df.duplicated().sum())
    print("Missing values:", df.isnull().sum().sum())

==================================================
Candidates
==================================================
Rows: 8441
Columns: 14
Duplicates: 0
Missing values: 0

==================================================
Results
==================================================
Rows: 8902
Columns: 10
Duplicates: 0
Missing values: 581

==================================================
Winners
==================================================
Rows: 543
Columns: 9
Duplicates: 0
Missing values: 3

In [39]:
# ============================================
# IMPORTANT ELECTION FIELDS
# ============================================

for name, df in datasets_clean.items():
    print(f"\n{'=' * 60}")
    print(name)
    print(f"{'=' * 60}")
    
    for column in df.columns:
        print(column)

============================================================
Candidates
============================================================
state
constituency_no
constituency
party
candidate_name
gender
age
address
application_date
application_status
father/husband's_name
photo_link
phase
polling_date

============================================================
Results
============================================================
state
pc_no
pc_name
sl_no
candidate
party
evm_votes
postal_votes
total_votes
vote_share

============================================================
Winners
============================================================
state
pc_no
pc_name
winning_candidate
winning_party
runner_up_canddiate
runner_up_party
margin_votes
results_status

In [40]:
# ============================================
# SAMPLE CLEANED DATA
# ============================================

display(candidates_clean.head())
display(results_clean.head())
display(winners_clean.head())

,state,constituency_no,constituency,party,candidate_name,gender,age,address,application_date,application_status,father/husband's_name,photo_link,phase,polling_date
0,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,V.K. ABDUL AZIZ,male,42,Brindaban,"27th March, 2024",Accepted,V.M. KOCHUNNI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
1,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,USHA KUMARI,female,39,"Dollygunj Village, Port Blair Tehsil, South An...","27th March, 2024",Accepted,S B GURUNG,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
2,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,RINKU MALA MONDAL,female,36,"Lokenath Colony, Dollygunj","27th March, 2024",Accepted,N N MONDAL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
3,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Indian National Congress,KULDEEP RAI SHARMA,male,56,"M.B.167, M.G. Road, Junglighat, Port Blair - 7...","27th March, 2024",Accepted,BHAGAT SINGH,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
4,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,ANAND RAMNATH ARLEKAR,male,58,"Panipath Road, Haddo","27th March, 2024",Accepted,RAMNATH ARLEKAR,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024

,state,pc_no,pc_name,sl_no,candidate,party,evm_votes,postal_votes,total_votes,vote_share
0,Andhra Pradesh,1,Araku (ST),1,GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,471470,5535,477005,40.96
1,Andhra Pradesh,1,Araku (ST),2,KOTHAPALLI GEETHA,Bharatiya Janata Party,417113,9312,426425,36.62
2,Andhra Pradesh,1,Araku (ST),3,APPALANARASA PACHIPENTA,Communist Party of India (Marxist),119016,4113,123129,10.57
3,Andhra Pradesh,1,Araku (ST),4,AVASHYA LAHARI . VARAM,Bahujan Samaj Party,24858,892,25750,2.21
4,Andhra Pradesh,1,Araku (ST),5,SAMAREDDY BALAKRISHNA,Independent,9493,42,9535,0.82

,state,pc_no,pc_name,winning_candidate,winning_party,runner_up_canddiate,runner_up_party,margin_votes,results_status
0,Andhra Pradesh,7,Amalapuram (SC),G M HARISH (BALAYOGI),Telugu Desam,RAPAKA VARAPRASADA RAO,Yuvajana Sramika Rythu Congress Party,342196,Result Declared
1,Andhra Pradesh,5,Anakapalle,C.M.RAMESH,Bharatiya Janata Party,BUDI MUTYALA NAIDU,Yuvajana Sramika Rythu Congress Party,296530,Result Declared
2,Andhra Pradesh,19,Ananthapur,AMBICA G LAKSHMINARAYANA VALMIKI,Telugu Desam,MALAGUNDLA SANKAR NARAYANA,Yuvajana Sramika Rythu Congress Party,188555,Result Declared
3,Andhra Pradesh,1,Araku (ST),GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,KOTHAPALLI GEETHA,Bharatiya Janata Party,50580,Result Declared
4,Andhra Pradesh,15,Bapatla (SC),KRISHNA PRASAD TENNETI,Telugu Desam,NANDIGAM SURESH BABU,Yuvajana Sramika Rythu Congress Party,208031,Result Declared

In [41]:
# ============================================
# MODULE 6: IDENTIFY ELECTION FIELDS
# ============================================

def find_columns(df):
    result = {}
    
    for column in df.columns:
        name = column.lower()
        
        if any(x in name for x in ["state", "st_name", "state_name"]):
            result.setdefault("state", []).append(column)
            
        if any(x in name for x in ["constituency", "pc_name", "pc_no"]):
            result.setdefault("constituency", []).append(column)
            
        if any(x in name for x in ["candidate", "cand_name"]):
            result.setdefault("candidate", []).append(column)
            
        if any(x in name for x in ["party", "partyname", "party_name"]):
            result.setdefault("party", []).append(column)
            
        if any(x in name for x in ["vote", "votes", "totvotpoll"]):
            result.setdefault("votes", []).append(column)
            
        if any(x in name for x in ["elector", "electors"]):
            result.setdefault("electors", []).append(column)
            
        if any(x in name for x in ["margin", "majority"]):
            result.setdefault("margin", []).append(column)
    
    return result


for name, df in datasets_clean.items():
    print(f"\n{'=' * 60}")
    print(name)
    print(f"{'=' * 60}")
    
    fields = find_columns(df)
    
    for field, columns in fields.items():
        print(f"{field:15} → {columns}")

============================================================
Candidates
============================================================
state           → ['state']
constituency    → ['constituency_no', 'constituency']
party           → ['party']
candidate       → ['candidate_name']

============================================================
Results
============================================================
state           → ['state']
constituency    → ['pc_no', 'pc_name']
candidate       → ['candidate']
party           → ['party']
votes           → ['evm_votes', 'postal_votes', 'total_votes', 'vote_share']

============================================================
Winners
============================================================
state           → ['state']
constituency    → ['pc_no', 'pc_name']
candidate       → ['winning_candidate']
party           → ['winning_party', 'runner_up_party']
votes           → ['margin_votes']
margin          → ['margin_votes']

In [42]:
# ============================================
# CANDIDATE DATA ANALYSIS
# ============================================

print("Candidates dataset shape:")
print(candidates_clean.shape)

print("\nCandidates columns:")
print(candidates_clean.columns.tolist())

display(candidates_clean.head(10))

Candidates dataset shape:
(8441, 14)

Candidates columns:
['state', 'constituency_no', 'constituency', 'party', 'candidate_name', 'gender', 'age', 'address', 'application_date', 'application_status', "father/husband's_name", 'photo_link', 'phase', 'polling_date']

,state,constituency_no,constituency,party,candidate_name,gender,age,address,application_date,application_status,father/husband's_name,photo_link,phase,polling_date
0,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,V.K. ABDUL AZIZ,male,42,Brindaban,"27th March, 2024",Accepted,V.M. KOCHUNNI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
1,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,USHA KUMARI,female,39,"Dollygunj Village, Port Blair Tehsil, South An...","27th March, 2024",Accepted,S B GURUNG,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
2,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,RINKU MALA MONDAL,female,36,"Lokenath Colony, Dollygunj","27th March, 2024",Accepted,N N MONDAL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
3,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Indian National Congress,KULDEEP RAI SHARMA,male,56,"M.B.167, M.G. Road, Junglighat, Port Blair - 7...","27th March, 2024",Accepted,BHAGAT SINGH,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
4,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,ANAND RAMNATH ARLEKAR,male,58,"Panipath Road, Haddo","27th March, 2024",Accepted,RAMNATH ARLEKAR,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
5,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,K VENKAT RAM BABU,male,50,Wimberlygunj,"27th March, 2024",Accepted,K THATHAYYA,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
6,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Socialist Unity Centre Of India (COMMUNIST),SALAMAT MONDAL,male,48,"Garacharma-II, Bathu Basti, Port Blair, South ...","27th March, 2024",Accepted,YEAD ALI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
7,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,All India Anna Dravida Munnetra Kazhagam,K J B SELVARAJ,male,50,"ALAN HOUSE, NEAR SONY TILES GODOWN, DOLLYGUNJ,...","26th March, 2024",Accepted,G KULANDAI SAMY,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
8,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Andaman Nicobar Democratic Congress,MANOJ PAUL,male,35,"MADHUPUR-1, DIGLIPUR, NORTH ANDAMAN, A AND N I...","26th March, 2024",Accepted,NIRODE BIHARI PAUL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
9,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Communist Party of India (Marxist),D AYYAPPAN,male,60,"FLAT NO. 32, G BLOCK D AND K CITY, PORT BLAIR ...","26th March, 2024",Accepted,P DAMODARAN,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024

In [43]:
# ============================================
# CANDIDATE DATA NUMERICAL SUMMARY
# ============================================

display(candidates_clean.describe(include="all"))

,state,constituency_no,constituency,party,candidate_name,gender,age,address,application_date,application_status,father/husband's_name,photo_link,phase,polling_date
count,8441,8441.000000,8441,8441,8441,8441,8441.000000,8441,8441,8441,8441,8441,8441.000000,8441
unique,36,NaN,541,749,8105,3,NaN,8360,40,1,7835,8367,NaN,9
top,Maharashtra,NaN,KARUR,Independent,MANOJ KUMAR,male,NaN,"Door NO 13-1-90, Putta Veedhi, Mettakkivalasa,...","27th March, 2024",Accepted,ARUMUGAM,https://results.eci.gov.in/uploads4/candprofil...,NaN,19-04-2024
freq,1163,NaN,54,3981,11,7634,NaN,2,724,8441,11,2,NaN,1864
mean,NaN,17.475773,NaN,NaN,NaN,NaN,47.760455,NaN,NaN,NaN,NaN,NaN,3.537732,NaN
std,NaN,15.252105,NaN,NaN,NaN,NaN,11.972568,NaN,NaN,NaN,NaN,NaN,1.968419,NaN
min,NaN,1.000000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
25%,NaN,6.000000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,NaN,2.000000,NaN
50%,NaN,13.000000,NaN,NaN,NaN,NaN,47.000000,NaN,NaN,NaN,NaN,NaN,3.000000,NaN
75%,NaN,25.000000,NaN,NaN,NaN,NaN,56.000000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN
max,NaN,80.000000,NaN,NaN,NaN,NaN,88.000000,NaN,NaN,NaN,NaN,NaN,7.000000,NaN

In [44]:
# ============================================
# WINNER DATA ANALYSIS
# ============================================

print("Winners dataset shape:")
print(winners_clean.shape)

print("\nWinners columns:")
print(winners_clean.columns.tolist())

display(winners_clean.head(10))

Winners dataset shape:
(543, 9)

Winners columns:
['state', 'pc_no', 'pc_name', 'winning_candidate', 'winning_party', 'runner_up_canddiate', 'runner_up_party', 'margin_votes', 'results_status']

,state,pc_no,pc_name,winning_candidate,winning_party,runner_up_canddiate,runner_up_party,margin_votes,results_status
0,Andhra Pradesh,7,Amalapuram (SC),G M HARISH (BALAYOGI),Telugu Desam,RAPAKA VARAPRASADA RAO,Yuvajana Sramika Rythu Congress Party,342196,Result Declared
1,Andhra Pradesh,5,Anakapalle,C.M.RAMESH,Bharatiya Janata Party,BUDI MUTYALA NAIDU,Yuvajana Sramika Rythu Congress Party,296530,Result Declared
2,Andhra Pradesh,19,Ananthapur,AMBICA G LAKSHMINARAYANA VALMIKI,Telugu Desam,MALAGUNDLA SANKAR NARAYANA,Yuvajana Sramika Rythu Congress Party,188555,Result Declared
3,Andhra Pradesh,1,Araku (ST),GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,KOTHAPALLI GEETHA,Bharatiya Janata Party,50580,Result Declared
4,Andhra Pradesh,15,Bapatla (SC),KRISHNA PRASAD TENNETI,Telugu Desam,NANDIGAM SURESH BABU,Yuvajana Sramika Rythu Congress Party,208031,Result Declared
5,Andhra Pradesh,25,Chittoor(SC),DAGGUMALLA PRASADA RAO,Telugu Desam,REDDEPPA.N .,Yuvajana Sramika Rythu Congress Party,220479,Result Declared
6,Andhra Pradesh,10,Eluru,PUTTA MAHESH KUMAR,Telugu Desam,KARUMURI SUNIL KUMAR,Yuvajana Sramika Rythu Congress Party,181857,Result Declared
7,Andhra Pradesh,13,Guntur,DR CHANDRA SEKHAR PEMMASANI,Telugu Desam,KILARI VENKATA ROSAIAH,Yuvajana Sramika Rythu Congress Party,344695,Result Declared
8,Andhra Pradesh,20,Hindupur,B K PARTHASARATHI,Telugu Desam,J SHANTHA,Yuvajana Sramika Rythu Congress Party,132427,Result Declared
9,Andhra Pradesh,21,Kadapa,Y. S. AVINASH REDDY,Yuvajana Sramika Rythu Congress Party,CHADIPIRALLA BHUPESH SUBBARAMI REDDY,Telugu Desam,62695,Result Declared

In [45]:
# ============================================
# RESULTS DATA ANALYSIS
# ============================================

print("Results dataset shape:")
print(results_clean.shape)

print("\nResults columns:")
print(results_clean.columns.tolist())

display(results_clean.head(10))

Results dataset shape:
(8902, 10)

Results columns:
['state', 'pc_no', 'pc_name', 'sl_no', 'candidate', 'party', 'evm_votes', 'postal_votes', 'total_votes', 'vote_share']

,state,pc_no,pc_name,sl_no,candidate,party,evm_votes,postal_votes,total_votes,vote_share
0,Andhra Pradesh,1,Araku (ST),1,GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,471470,5535,477005,40.96
1,Andhra Pradesh,1,Araku (ST),2,KOTHAPALLI GEETHA,Bharatiya Janata Party,417113,9312,426425,36.62
2,Andhra Pradesh,1,Araku (ST),3,APPALANARASA PACHIPENTA,Communist Party of India (Marxist),119016,4113,123129,10.57
3,Andhra Pradesh,1,Araku (ST),4,AVASHYA LAHARI . VARAM,Bahujan Samaj Party,24858,892,25750,2.21
4,Andhra Pradesh,1,Araku (ST),5,SAMAREDDY BALAKRISHNA,Independent,9493,42,9535,0.82
5,Andhra Pradesh,1,Araku (ST),6,NIMMAKA JAYARAJU,Independent,8798,664,9462,0.81
6,Andhra Pradesh,1,Araku (ST),7,ATHIDHI,Independent,8121,15,8136,0.7
7,Andhra Pradesh,1,Araku (ST),8,CHANTI BADNAINA,Jai Bharat National Party,7205,47,7252,0.62
8,Andhra Pradesh,1,Araku (ST),9,MOTTADAM . RAJABABU,Bharat Adivasi Party,6370,396,6766,0.58
9,Andhra Pradesh,1,Araku (ST),10,RANJITH KUMAR PALAKA,Independent,6000,47,6047,0.52

In [46]:
# ============================================
# MODULE 6: CREATE CLEAN CANDIDATE DATA
# ============================================

lok_sabha_clean = candidates_clean.copy()

print("Clean Lok Sabha dataset created.")
print("Rows   :", lok_sabha_clean.shape[0])
print("Columns:", lok_sabha_clean.shape[1])

Clean Lok Sabha dataset created.
Rows   : 8441
Columns: 14

In [47]:
display(lok_sabha_clean.head())

,state,constituency_no,constituency,party,candidate_name,gender,age,address,application_date,application_status,father/husband's_name,photo_link,phase,polling_date
0,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,V.K. ABDUL AZIZ,male,42,Brindaban,"27th March, 2024",Accepted,V.M. KOCHUNNI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
1,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,USHA KUMARI,female,39,"Dollygunj Village, Port Blair Tehsil, South An...","27th March, 2024",Accepted,S B GURUNG,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
2,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,RINKU MALA MONDAL,female,36,"Lokenath Colony, Dollygunj","27th March, 2024",Accepted,N N MONDAL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
3,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Indian National Congress,KULDEEP RAI SHARMA,male,56,"M.B.167, M.G. Road, Junglighat, Port Blair - 7...","27th March, 2024",Accepted,BHAGAT SINGH,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
4,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,ANAND RAMNATH ARLEKAR,male,58,"Panipath Road, Haddo","27th March, 2024",Accepted,RAMNATH ARLEKAR,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024

In [48]:
# ============================================
# CANDIDATE UNIQUENESS CHECK
# ============================================

print("Total candidate records:", len(lok_sabha_clean))

print(
    "Duplicate candidate records:",
    lok_sabha_clean.duplicated().sum()
)

Total candidate records: 8441
Duplicate candidate records: 0

In [49]:
# ============================================
# CHECK IDENTIFIER COLUMNS
# ============================================

for column in lok_sabha_clean.columns:
    unique_count = lok_sabha_clean[column].nunique()
    
    print(
        f"{column:<30} "
        f"Unique: {unique_count:,} "
        f"Total: {len(lok_sabha_clean):,}"
    )

state                          Unique: 36 Total: 8,441
constituency_no                Unique: 80 Total: 8,441
constituency                   Unique: 541 Total: 8,441
party                          Unique: 749 Total: 8,441
candidate_name                 Unique: 8,105 Total: 8,441
gender                         Unique: 3 Total: 8,441
age                            Unique: 63 Total: 8,441
address                        Unique: 8,360 Total: 8,441
application_date               Unique: 40 Total: 8,441
application_status             Unique: 1 Total: 8,441
father/husband's_name          Unique: 7,835 Total: 8,441
photo_link                     Unique: 8,367 Total: 8,441
phase                          Unique: 7 Total: 8,441
polling_date                   Unique: 9 Total: 8,441

In [50]:
# ============================================
# SAVE CLEAN CANDIDATE DATA
# ============================================

output_path = PROCESSED_DATA / "lok_sabha_clean.csv"

lok_sabha_clean.to_csv(
    output_path,
    index=False
)

print("Saved successfully:")
print(output_path.resolve())

Saved successfully:
C:\Users\mural\Indian_Election_Analysis\data\processed\lok_sabha_clean.csv

In [51]:
# ============================================
# VERIFY SAVED DATA
# ============================================

test_df = pd.read_csv(output_path)

print("File loaded successfully.")
print("Shape:", test_df.shape)

display(test_df.head())

File loaded successfully.
Shape: (8441, 14)

,state,constituency_no,constituency,party,candidate_name,gender,age,address,application_date,application_status,father/husband's_name,photo_link,phase,polling_date
0,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,V.K. ABDUL AZIZ,male,42,Brindaban,"27th March, 2024",Accepted,V.M. KOCHUNNI,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
1,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,USHA KUMARI,female,39,"Dollygunj Village, Port Blair Tehsil, South An...","27th March, 2024",Accepted,S B GURUNG,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
2,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,RINKU MALA MONDAL,female,36,"Lokenath Colony, Dollygunj","27th March, 2024",Accepted,N N MONDAL,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
3,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Indian National Congress,KULDEEP RAI SHARMA,male,56,"M.B.167, M.G. Road, Junglighat, Port Blair - 7...","27th March, 2024",Accepted,BHAGAT SINGH,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024
4,Andaman & Nicobar Islands,1,Andaman & Nicobar Islands,Independent,ANAND RAMNATH ARLEKAR,male,58,"Panipath Road, Haddo","27th March, 2024",Accepted,RAMNATH ARLEKAR,https://results.eci.gov.in/uploads4/candprofil...,1,19-04-2024

In [52]:
# ============================================
# MODULE 10: WINNER DATA
# ============================================

winner_data = winners_clean.copy()

print("Winner dataset loaded into working DataFrame.")
print("Rows   :", winner_data.shape[0])
print("Columns:", winner_data.shape[1])

Winner dataset loaded into working DataFrame.
Rows   : 543
Columns: 9

In [53]:
# ============================================
# WINNER DATA PREVIEW
# ============================================

display(winner_data.head(10))

,state,pc_no,pc_name,winning_candidate,winning_party,runner_up_canddiate,runner_up_party,margin_votes,results_status
0,Andhra Pradesh,7,Amalapuram (SC),G M HARISH (BALAYOGI),Telugu Desam,RAPAKA VARAPRASADA RAO,Yuvajana Sramika Rythu Congress Party,342196,Result Declared
1,Andhra Pradesh,5,Anakapalle,C.M.RAMESH,Bharatiya Janata Party,BUDI MUTYALA NAIDU,Yuvajana Sramika Rythu Congress Party,296530,Result Declared
2,Andhra Pradesh,19,Ananthapur,AMBICA G LAKSHMINARAYANA VALMIKI,Telugu Desam,MALAGUNDLA SANKAR NARAYANA,Yuvajana Sramika Rythu Congress Party,188555,Result Declared
3,Andhra Pradesh,1,Araku (ST),GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,KOTHAPALLI GEETHA,Bharatiya Janata Party,50580,Result Declared
4,Andhra Pradesh,15,Bapatla (SC),KRISHNA PRASAD TENNETI,Telugu Desam,NANDIGAM SURESH BABU,Yuvajana Sramika Rythu Congress Party,208031,Result Declared
5,Andhra Pradesh,25,Chittoor(SC),DAGGUMALLA PRASADA RAO,Telugu Desam,REDDEPPA.N .,Yuvajana Sramika Rythu Congress Party,220479,Result Declared
6,Andhra Pradesh,10,Eluru,PUTTA MAHESH KUMAR,Telugu Desam,KARUMURI SUNIL KUMAR,Yuvajana Sramika Rythu Congress Party,181857,Result Declared
7,Andhra Pradesh,13,Guntur,DR CHANDRA SEKHAR PEMMASANI,Telugu Desam,KILARI VENKATA ROSAIAH,Yuvajana Sramika Rythu Congress Party,344695,Result Declared
8,Andhra Pradesh,20,Hindupur,B K PARTHASARATHI,Telugu Desam,J SHANTHA,Yuvajana Sramika Rythu Congress Party,132427,Result Declared
9,Andhra Pradesh,21,Kadapa,Y. S. AVINASH REDDY,Yuvajana Sramika Rythu Congress Party,CHADIPIRALLA BHUPESH SUBBARAMI REDDY,Telugu Desam,62695,Result Declared

In [54]:
# ============================================
# WINNER COLUMNS
# ============================================

print("Winner columns:")
print(winner_data.columns.tolist())

Winner columns:
['state', 'pc_no', 'pc_name', 'winning_candidate', 'winning_party', 'runner_up_canddiate', 'runner_up_party', 'margin_votes', 'results_status']

In [55]:
# ============================================
# FIND PARTY-RELATED COLUMNS
# ============================================

party_columns = [
    col for col in winner_data.columns
    if "party" in col.lower()
    or "partyname" in col.lower()
    or "party_name" in col.lower()
    or "partyabbre" in col.lower()
]

print("Possible party columns:")
print(party_columns)

Possible party columns:
['winning_party', 'runner_up_party']

In [56]:
# ============================================
# WINNER DUPLICATE CHECK
# ============================================

print(
    "Total winner records:",
    len(winner_data)
)

print(
    "Duplicate records:",
    winner_data.duplicated().sum()
)

Total winner records: 543
Duplicate records: 0

In [57]:
# ============================================
# IDENTIFY WINNER FIELDS
# ============================================

for column in winner_data.columns:
    
    column_lower = column.lower()
    
    if any(keyword in column_lower for keyword in [
        "state",
        "const",
        "pc",
        "candidate",
        "winner",
        "party",
        "vote",
        "margin",
        "majority",
        "elector"
    ]):
        print(column)

state
pc_no
pc_name
winning_candidate
winning_party
runner_up_party
margin_votes

In [58]:
# ============================================
# CONSTITUENCY COUNT
# ============================================

print(
    "Unique constituencies:",
    winner_data["pc_name"].nunique()
)

Unique constituencies: 541

In [59]:
# ============================================
# STATE COUNT
# ============================================

print(
    "Unique states:",
    winner_data["state"].nunique()
)

print("\nStates:")
print(
    sorted(
        winner_data["state"]
        .dropna()
        .unique()
    )
)

Unique states: 36

States:
['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli and Daman & Diu', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'NCT OF Delhi', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [60]:
# ============================================
# PARTY-WISE SEAT COUNT
# ============================================

party_seats = (
    winner_data
    .groupby("winning_party")
    .size()
    .sort_values(ascending=False)
)

print("Party-wise seats won in Lok Sabha 2024:")
display(party_seats)

Party-wise seats won in Lok Sabha 2024:

winning_party
Bharatiya Janata Party                                        240
Indian National Congress                                       99
Samajwadi Party                                                37
All India Trinamool Congress                                   29
Dravida Munnetra Kazhagam                                      22
Telugu Desam                                                   16
Janata Dal  (United)                                           12
Shiv Sena (Uddhav Balasaheb Thackrey)                           9
Nationalist Congress Party – Sharadchandra Pawar                8
Independent                                                     7
Shiv Sena                                                       7
Lok Janshakti Party(Ram Vilas)                                  5
Yuvajana Sramika Rythu Congress Party                           4
Rashtriya Janata Dal                                            4
Communist Party of India  (Marxist)                             4
Indian Union Muslim League                                      3
Jharkhand Mukti Morcha                                          3
Aam Aadmi Party                                                 3
Viduthalai Chiruthaigal Katchi                                  2
Communist Party of India  (Marxist-Leninist)  (Liberation)      2
Jammu & Kashmir National Conference                             2
Rashtriya Lok Dal                                               2
Janata Dal  (Secular)                                           2
Janasena Party                                                  2
Communist Party of India                                        2
AJSU Party                                                      1
Asom Gana Parishad                                              1
Bharat Adivasi Party                                            1
All India Majlis-E-Ittehadul Muslimeen                          1
Apna Dal (Soneylal)                                             1
Aazad Samaj Party (Kanshi Ram)                                  1
Marumalarchi Dravida Munnetra Kazhagam                          1
Kerala Congress                                                 1
Hindustani Awam Morcha (Secular)                                1
Nationalist Congress Party                                      1
Shiromani Akali Dal                                             1
Rashtriya Loktantrik Party                                      1
Revolutionary Socialist Party                                   1
United People’s Party, Liberal                                  1
Sikkim Krantikari Morcha                                        1
Voice of the People Party                                       1
Zoram People’s Movement                                         1
dtype: int64

In [61]:
# ============================================
# PARTY SEAT DATAFRAME
# ============================================

party_seats_df = (
    party_seats
    .reset_index(name="seats_won")
    .rename(columns={"winning_party": "party"})
)

display(party_seats_df)

                                                party  seats_won
0                              Bharatiya Janata Party        240
1                            Indian National Congress         99
2                                     Samajwadi Party         37
3                        All India Trinamool Congress         29
4                           Dravida Munnetra Kazhagam         22
5                                        Telugu Desam         16
6                                Janata Dal  (United)         12
7               Shiv Sena (Uddhav Balasaheb Thackrey)          9
8    Nationalist Congress Party – Sharadchandra Pawar          8
9                                         Independent          7
10                                          Shiv Sena          7
11                     Lok Janshakti Party(Ram Vilas)          5
12              Yuvajana Sramika Rythu Congress Party          4
13                               Rashtriya Janata Dal          4
14                Communist Party of India  (Marxist)          4
15                         Indian Union Muslim League          3
16                             Jharkhand Mukti Morcha          3
17                                    Aam Aadmi Party          3
18                     Viduthalai Chiruthaigal Katchi          2
19  Communist Party of India  (Marxist-Leninist)  ...          2
20                Jammu & Kashmir National Conference          2
21                                  Rashtriya Lok Dal          2
22                              Janata Dal  (Secular)          2
23                                     Janasena Party          2
24                           Communist Party of India          2
25                                         AJSU Party          1
26                                 Asom Gana Parishad          1
27                               Bharat Adivasi Party          1
28             All India Majlis-E-Ittehadul Muslimeen          1
29                                Apna Dal (Soneylal)          1
30                     Aazad Samaj Party (Kanshi Ram)          1
31             Marumalarchi Dravida Munnetra Kazhagam          1
32                                    Kerala Congress          1
33                   Hindustani Awam Morcha (Secular)          1
34                         Nationalist Congress Party          1
35                                Shiromani Akali Dal          1
36                         Rashtriya Loktantrik Party          1
37                      Revolutionary Socialist Party          1
38                     United People’s Party, Liberal          1
39                           Sikkim Krantikari Morcha          1
40                          Voice of the People Party          1
41                            Zoram People’s Movement          1

In [62]:
# ============================================
# FIND STATE COLUMN
# ============================================

state_columns = [
    col for col in winner_data.columns
    if "state" in col.lower()
    or "st_name" in col.lower()
    or col.lower() == "st"
]

print("Possible state columns:")
print(state_columns)

Possible state columns:
['state']

In [63]:
# ============================================
# STATE-WISE SEATS
# ============================================

state_column = state_columns[0]

state_seats = (
    winner_data
    .groupby(state_column)
    .size()
    .sort_values(ascending=False)
)

print("State-wise Lok Sabha seats:")
display(state_seats)

State-wise Lok Sabha seats:

state
Uttar Pradesh                           80
Maharashtra                             48
West Bengal                             42
Bihar                                   40
Tamil Nadu                              39
Madhya Pradesh                          29
Karnataka                               28
Gujarat                                 26
Rajasthan                               25
Andhra Pradesh                          25
Odisha                                  21
Kerala                                  20
Telangana                               17
Jharkhand                               14
Assam                                   14
Punjab                                  13
Chhattisgarh                            11
Haryana                                 10
NCT OF Delhi                             7
Uttarakhand                              5
Jammu and Kashmir                        5
Himachal Pradesh                         4
Meghalaya                                2
Arunachal Pradesh                        2
Dadra & Nagar Haveli and Daman & Diu     2
Manipur                                  2
Tripura                                  2
Goa                                      2
Andaman & Nicobar Islands                1
Ladakh                                   1
Chandigarh                               1
Lakshadweep                              1
Puducherry                               1
Nagaland                                 1
Mizoram                                  1
Sikkim                                   1
dtype: int64

In [64]:
# ============================================
# PARTY-WISE SEATS BY STATE
# ============================================

party_state_seats = (
    winner_data
    .groupby([state_column, "winning_party"])
    .size()
    .reset_index(name="seats_won")
    .sort_values(
        [state_column, "seats_won"],
        ascending=[True, False]
    )
)

display(party_state_seats.head(30))

                                   state                                      winning_party  seats_won
0              Andaman & Nicobar Islands                             Bharatiya Janata Party          1
3                         Andhra Pradesh                                       Telugu Desam         16
4                         Andhra Pradesh              Yuvajana Sramika Rythu Congress Party          4
1                         Andhra Pradesh                             Bharatiya Janata Party          3
2                         Andhra Pradesh                                     Janasena Party          2
5                      Arunachal Pradesh                             Bharatiya Janata Party          2
7                                  Assam                             Bharatiya Janata Party          9
8                                  Assam                           Indian National Congress          3
6                                  Assam                                 Asom Gana Parishad          1
9                                  Assam                     United People’s Party, Liberal          1
10                                 Bihar                             Bharatiya Janata Party         12
15                                 Bihar                               Janata Dal  (United)         12
16                                 Bihar                     Lok Janshakti Party(Ram Vilas)          5
17                                 Bihar                               Rashtriya Janata Dal          4
14                                 Bihar                           Indian National Congress          3
11                                 Bihar  Communist Party of India  (Marxist-Leninist)  ...          2
12                                 Bihar                   Hindustani Awam Morcha (Secular)          1
13                                 Bihar                                        Independent          1
18                            Chandigarh                           Indian National Congress          1
19                          Chhattisgarh                             Bharatiya Janata Party         10
20                          Chhattisgarh                           Indian National Congress          1
21  Dadra & Nagar Haveli and Daman & Diu                             Bharatiya Janata Party          1
22  Dadra & Nagar Haveli and Daman & Diu                                        Independent          1
23                                   Goa                             Bharatiya Janata Party          1
24                                   Goa                           Indian National Congress          1
25                               Gujarat                             Bharatiya Janata Party         25
26                               Gujarat                           Indian National Congress          1
27                               Haryana                             Bharatiya Janata Party          5
28                               Haryana                           Indian National Congress          5
29                      Himachal Pradesh                             Bharatiya Janata Party          4

In [65]:
# ============================================
# FIND CONSTITUENCY COLUMN
# ============================================

constituency_columns = [
    col for col in winner_data.columns
    if any(keyword in col.lower() for keyword in [
        "constituency",
        "pc_name",
        "pc_no",
        "seat"
    ])
]

print("Possible constituency columns:")

print(constituency_columns)

Possible constituency columns:
['pc_no', 'pc_name']

In [66]:
# ============================================
# SELECT CONSTITUENCY COLUMN
# ============================================

constituency_column = constituency_columns[0]

print("Using constituency column:", constituency_column)

Using constituency column: pc_no

In [67]:
# ============================================
# CHECK ALL WINNER COLUMNS
# ============================================

print("Winner columns:")
for i, col in enumerate(winner_data.columns, start=1):
    print(i, "->", col)

Winner columns:
1 -> state
2 -> pc_no
3 -> pc_name
4 -> winning_candidate
5 -> winning_party
6 -> runner_up_canddiate
7 -> runner_up_party
8 -> margin_votes
9 -> results_status

In [68]:
# ============================================
# UNIQUE VALUES BY COLUMN
# ============================================

for col in winner_data.columns:
    print(f"{col:<35} : {winner_data[col].nunique():,}")

state                               : 36
pc_no                               : 80
pc_name                             : 541
winning_candidate                   : 542
winning_party                       : 42
runner_up_canddiate                 : 542
runner_up_party                     : 42
margin_votes                        : 542
results_status                      : 2

In [69]:
# ============================================
# CHECK CURRENT CONSTITUENCY COLUMN
# ============================================

print("Current selected column:", constituency_column)

print("\nSample values:")
print(
    winner_data[constituency_column]
    .dropna()
    .unique()[:100]
)

Current selected column: pc_no

Sample values:
[ 7  5 19  1 15 25 10 13 20 21  6 18 11 17  9 14 22 16  8 24  2 23 12  4
  3 32 37 27 26 33 38 36 40 35 28 29 39 31 30 34 48 47 41 43 46 44 45 42
 52 55 69 56 72 67 53 61 78 76 66 60 54 49 75 70 59 64 73 57 50 65 68 74
 63 79 51 80 71 62 58 77]

In [70]:
# ============================================
# FIND CONSTITUENCY NAME COLUMN
# ============================================

for col in winner_data.columns:
    if any(keyword in col.lower() for keyword in [
        "pc_name",
        "constituency",
        "const_name",
        "seat_name"
    ]):
        print(col)

pc_name

In [71]:
# ============================================
# VALIDATE LOK SABHA CONSTITUENCIES
# ============================================

constituency_name_column = "pc_name"

total_constituencies = (
    winner_data[
        [state_column, constituency_name_column]
    ]
    .drop_duplicates()
    .shape[0]
)

print(
    "Unique State + Constituency combinations:",
    total_constituencies
)

Unique State + Constituency combinations: 543

In [72]:
# ============================================
# CHECK DUPLICATE CONSTITUENCIES
# ============================================

constituency_counts = (
    winner_data
    .groupby([state_column, constituency_name_column])
    .size()
)

print(
    "Total constituencies:",
    len(constituency_counts)
)

print(
    "Maximum records per constituency:",
    constituency_counts.max()
)

print(
    "Constituencies with multiple records:",
    (constituency_counts > 1).sum()
)

Total constituencies: 543
Maximum records per constituency: 1
Constituencies with multiple records: 0

In [73]:
# ============================================
# STATE-WISE LOK SABHA SEATS
# ============================================

state_seats_df = (
    winner_data
    .groupby(state_column)[constituency_name_column]
    .nunique()
    .reset_index(name="total_seats")
    .sort_values("total_seats", ascending=False)
)

display(state_seats_df)

                                   state  total_seats
33                         Uttar Pradesh           80
19                           Maharashtra           48
35                           West Bengal           42
4                                  Bihar           40
30                            Tamil Nadu           39
18                        Madhya Pradesh           29
14                             Karnataka           28
9                                Gujarat           26
28                             Rajasthan           25
1                         Andhra Pradesh           25
25                                Odisha           21
15                                Kerala           20
31                             Telangana           17
13                             Jharkhand           14
3                                  Assam           14
27                                Punjab           13
6                           Chhattisgarh           11
10                               Haryana           10
23                          NCT OF Delhi            7
34                           Uttarakhand            5
12                     Jammu and Kashmir            5
11                      Himachal Pradesh            4
21                             Meghalaya            2
2                      Arunachal Pradesh            2
7   Dadra & Nagar Haveli and Daman & Diu            2
20                               Manipur            2
32                               Tripura            2
8                                    Goa            2
0              Andaman & Nicobar Islands            1
16                                Ladakh            1
5                             Chandigarh            1
17                           Lakshadweep            1
26                            Puducherry            1
24                              Nagaland            1
22                               Mizoram            1
29                                Sikkim            1

In [74]:
# ============================================
# MODULE 12: FINAL LOK SABHA WINNER TABLE
# ============================================

winner_seats = (
    winner_data[
        [state_column, constituency_name_column, "winning_party"]
    ]
    .drop_duplicates()
    .copy()
)

print("Winner seat table created.")
print("Rows:", len(winner_seats))
print("Columns:", winner_seats.columns.tolist())

display(winner_seats.head())

Winner seat table created.
Rows: 543
Columns: ['state', 'pc_name', 'winning_party']

            state          pc_name                          winning_party
0  Andhra Pradesh  Amalapuram (SC)                           Telugu Desam
1  Andhra Pradesh       Anakapalle                 Bharatiya Janata Party
2  Andhra Pradesh       Ananthapur                           Telugu Desam
3  Andhra Pradesh       Araku (ST)  Yuvajana Sramika Rythu Congress Party
4  Andhra Pradesh     Bapatla (SC)                           Telugu Desam

In [75]:
# ============================================
# STANDARDIZE WINNER TABLE
# ============================================

winner_seats = winner_seats.rename(columns={
    state_column: "state",
    constituency_name_column: "constituency",
    "winning_party": "winning_party"
})

display(winner_seats.head())

            state     constituency                          winning_party
0  Andhra Pradesh  Amalapuram (SC)                           Telugu Desam
1  Andhra Pradesh       Anakapalle                 Bharatiya Janata Party
2  Andhra Pradesh       Ananthapur                           Telugu Desam
3  Andhra Pradesh       Araku (ST)  Yuvajana Sramika Rythu Congress Party
4  Andhra Pradesh     Bapatla (SC)                           Telugu Desam

In [76]:
# ============================================
# PARTY-WISE SEATS
# ============================================

party_seats_df = (
    winner_seats
    .groupby("winning_party")
    .size()
    .reset_index(name="seats_won")
    .sort_values("seats_won", ascending=False)
)

display(party_seats_df)

                                        winning_party  seats_won
8                              Bharatiya Janata Party        240
15                           Indian National Congress         99
31                                    Samajwadi Party         37
4                        All India Trinamool Congress         29
12                          Dravida Munnetra Kazhagam         22
36                                       Telugu Desam         16
20                               Janata Dal  (United)         12
34              Shiv Sena (Uddhav Balasaheb Thackrey)          9
26   Nationalist Congress Party – Sharadchandra Pawar          8
14                                        Independent          7
33                                          Shiv Sena          7
23                     Lok Janshakti Party(Ram Vilas)          5
40              Yuvajana Sramika Rythu Congress Party          4
27                               Rashtriya Janata Dal          4
10                Communist Party of India  (Marxist)          4
16                         Indian Union Muslim League          3
21                             Jharkhand Mukti Morcha          3
1                                     Aam Aadmi Party          3
38                     Viduthalai Chiruthaigal Katchi          2
11  Communist Party of India  (Marxist-Leninist)  ...          2
17                Jammu & Kashmir National Conference          2
28                                  Rashtriya Lok Dal          2
19                              Janata Dal  (Secular)          2
18                                     Janasena Party          2
9                            Communist Party of India          2
0                                          AJSU Party          1
6                                  Asom Gana Parishad          1
7                                Bharat Adivasi Party          1
3              All India Majlis-E-Ittehadul Muslimeen          1
5                                 Apna Dal (Soneylal)          1
2                      Aazad Samaj Party (Kanshi Ram)          1
24             Marumalarchi Dravida Munnetra Kazhagam          1
22                                    Kerala Congress          1
13                   Hindustani Awam Morcha (Secular)          1
25                         Nationalist Congress Party          1
32                                Shiromani Akali Dal          1
29                         Rashtriya Loktantrik Party          1
30                      Revolutionary Socialist Party          1
37                     United People’s Party, Liberal          1
35                           Sikkim Krantikari Morcha          1
39                          Voice of the People Party          1
41                            Zoram People’s Movement          1

In [77]:
# ============================================
# STATE-WISE SEATS
# ============================================

state_seats_df = (
    winner_seats
    .groupby("state")
    .size()
    .reset_index(name="total_seats")
    .sort_values("total_seats", ascending=False)
)

display(state_seats_df)

                                   state  total_seats
33                         Uttar Pradesh           80
19                           Maharashtra           48
35                           West Bengal           42
4                                  Bihar           40
30                            Tamil Nadu           39
18                        Madhya Pradesh           29
14                             Karnataka           28
9                                Gujarat           26
28                             Rajasthan           25
1                         Andhra Pradesh           25
25                                Odisha           21
15                                Kerala           20
31                             Telangana           17
13                             Jharkhand           14
3                                  Assam           14
27                                Punjab           13
6                           Chhattisgarh           11
10                               Haryana           10
23                          NCT OF Delhi            7
34                           Uttarakhand            5
12                     Jammu and Kashmir            5
11                      Himachal Pradesh            4
21                             Meghalaya            2
2                      Arunachal Pradesh            2
7   Dadra & Nagar Haveli and Daman & Diu            2
20                               Manipur            2
32                               Tripura            2
8                                    Goa            2
0              Andaman & Nicobar Islands            1
16                                Ladakh            1
5                             Chandigarh            1
17                           Lakshadweep            1
26                            Puducherry            1
24                              Nagaland            1
22                               Mizoram            1
29                                Sikkim            1

In [78]:
# ============================================
# STATE-WISE SEATS
# ============================================

state_seats_df = (
    winner_seats
    .groupby("state")
    .size()
    .reset_index(name="total_seats")
    .sort_values("total_seats", ascending=False)
)

display(state_seats_df)

                                   state  total_seats
33                         Uttar Pradesh           80
19                           Maharashtra           48
35                           West Bengal           42
4                                  Bihar           40
30                            Tamil Nadu           39
18                        Madhya Pradesh           29
14                             Karnataka           28
9                                Gujarat           26
28                             Rajasthan           25
1                         Andhra Pradesh           25
25                                Odisha           21
15                                Kerala           20
31                             Telangana           17
13                             Jharkhand           14
3                                  Assam           14
27                                Punjab           13
6                           Chhattisgarh           11
10                               Haryana           10
23                          NCT OF Delhi            7
34                           Uttarakhand            5
12                     Jammu and Kashmir            5
11                      Himachal Pradesh            4
21                             Meghalaya            2
2                      Arunachal Pradesh            2
7   Dadra & Nagar Haveli and Daman & Diu            2
20                               Manipur            2
32                               Tripura            2
8                                    Goa            2
0              Andaman & Nicobar Islands            1
16                                Ladakh            1
5                             Chandigarh            1
17                           Lakshadweep            1
26                            Puducherry            1
24                              Nagaland            1
22                               Mizoram            1
29                                Sikkim            1

In [79]:
# ============================================
# PARTY-WISE SEATS BY STATE
# ============================================

party_state_seats_df = (
    winner_seats
    .groupby(["state", "winning_party"])
    .size()
    .reset_index(name="seats_won")
    .sort_values(
        ["state", "seats_won"],
        ascending=[True, False]
    )
)

display(party_state_seats_df.head(30))

                                   state                                      winning_party  seats_won
0              Andaman & Nicobar Islands                             Bharatiya Janata Party          1
3                         Andhra Pradesh                                       Telugu Desam         16
4                         Andhra Pradesh              Yuvajana Sramika Rythu Congress Party          4
1                         Andhra Pradesh                             Bharatiya Janata Party          3
2                         Andhra Pradesh                                     Janasena Party          2
5                      Arunachal Pradesh                             Bharatiya Janata Party          2
7                                  Assam                             Bharatiya Janata Party          9
8                                  Assam                           Indian National Congress          3
6                                  Assam                                 Asom Gana Parishad          1
9                                  Assam                     United People’s Party, Liberal          1
10                                 Bihar                             Bharatiya Janata Party         12
15                                 Bihar                               Janata Dal  (United)         12
16                                 Bihar                     Lok Janshakti Party(Ram Vilas)          5
17                                 Bihar                               Rashtriya Janata Dal          4
14                                 Bihar                           Indian National Congress          3
11                                 Bihar  Communist Party of India  (Marxist-Leninist)  ...          2
12                                 Bihar                   Hindustani Awam Morcha (Secular)          1
13                                 Bihar                                        Independent          1
18                            Chandigarh                           Indian National Congress          1
19                          Chhattisgarh                             Bharatiya Janata Party         10
20                          Chhattisgarh                           Indian National Congress          1
21  Dadra & Nagar Haveli and Daman & Diu                             Bharatiya Janata Party          1
22  Dadra & Nagar Haveli and Daman & Diu                                        Independent          1
23                                   Goa                             Bharatiya Janata Party          1
24                                   Goa                           Indian National Congress          1
25                               Gujarat                             Bharatiya Janata Party         25
26                               Gujarat                           Indian National Congress          1
27                               Haryana                             Bharatiya Janata Party          5
28                               Haryana                           Indian National Congress          5
29                      Himachal Pradesh                             Bharatiya Janata Party          4

In [80]:
# ============================================
# FINAL SEAT VALIDATION
# ============================================

total_seats = winner_seats.shape[0]

print("Total Lok Sabha seats:", total_seats)

if total_seats == 543:
    print("✅ Validation successful: 543 constituencies found.")
else:
    print("⚠️ Seat count needs investigation.")

Total Lok Sabha seats: 543
✅ Validation successful: 543 constituencies found.

In [81]:
# ============================================
# SAVE WINNER SEAT TABLE
# ============================================

winner_seats_path = (
    PROCESSED_DATA / "lok_sabha_2024_winners.csv"
)

winner_seats.to_csv(
    winner_seats_path,
    index=False
)

print("Saved successfully:")
print(winner_seats_path.resolve())

Saved successfully:
C:\Users\mural\Indian_Election_Analysis\data\processed\lok_sabha_2024_winners.csv

In [82]:
# ============================================
# SAVE WINNER SEAT TABLE
# ============================================

winner_seats_path = (
    PROCESSED_DATA / "lok_sabha_2024_winners.csv"
)

winner_seats.to_csv(
    winner_seats_path,
    index=False
)

print("Saved successfully:")
print(winner_seats_path.resolve())

Saved successfully:
C:\Users\mural\Indian_Election_Analysis\data\processed\lok_sabha_2024_winners.csv

In [83]:
# ============================================
# FIND VOTE / ELECTOR / MARGIN COLUMNS
# ============================================

for name, df in {
    "Candidates": candidates_clean,
    "Results": results_clean,
    "Winners": winner_data
}.items():

    print(f"\n{'=' * 50}")
    print(name)
    print(f"{'=' * 50}")

    for column in df.columns:

        if any(keyword in column.lower() for keyword in [
            "vote",
            "elector",
            "poll",
            "margin",
            "majority",
            "turnout"
        ]):
            print(column)

==================================================
Candidates
==================================================
polling_date

==================================================
Results
==================================================
evm_votes
postal_votes
total_votes
vote_share

==================================================
Winners
==================================================
margin_votes

In [84]:
# ============================================
# FIND ACTUAL VOTE COLUMNS
# ============================================

print("Candidates columns:")
print(candidates_clean.columns.tolist())

print("\nPossible vote-related columns:")

for col in candidates_clean.columns:
    if any(word in col.lower() for word in [
        "vote",
        "poll",
        "elect",
        "result"
    ]):
        print("→", col)

Candidates columns:
['state', 'constituency_no', 'constituency', 'party', 'candidate_name', 'gender', 'age', 'address', 'application_date', 'application_status', "father/husband's_name", 'photo_link', 'phase', 'polling_date']

Possible vote-related columns:
→ polling_date

In [85]:
# ============================================
# MODULE 18: INSPECT 2024 RESULTS DATA
# ============================================

print("Results columns:")
print(results_clean.columns.tolist())

print("\nResults shape:")
print(results_clean.shape)

print("\nFirst 5 rows:")
display(results_clean.head())

Results columns:
['state', 'pc_no', 'pc_name', 'sl_no', 'candidate', 'party', 'evm_votes', 'postal_votes', 'total_votes', 'vote_share']

Results shape:
(8902, 10)

First 5 rows:

,state,pc_no,pc_name,sl_no,candidate,party,evm_votes,postal_votes,total_votes,vote_share
0,Andhra Pradesh,1,Araku (ST),1,GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,471470,5535,477005,40.96
1,Andhra Pradesh,1,Araku (ST),2,KOTHAPALLI GEETHA,Bharatiya Janata Party,417113,9312,426425,36.62
2,Andhra Pradesh,1,Araku (ST),3,APPALANARASA PACHIPENTA,Communist Party of India (Marxist),119016,4113,123129,10.57
3,Andhra Pradesh,1,Araku (ST),4,AVASHYA LAHARI . VARAM,Bahujan Samaj Party,24858,892,25750,2.21
4,Andhra Pradesh,1,Araku (ST),5,SAMAREDDY BALAKRISHNA,Independent,9493,42,9535,0.82

In [86]:
# ============================================
# FIND RESULT-RELATED COLUMNS
# ============================================

print("Possible vote/result columns:")

for col in results_clean.columns:
    if any(word in col.lower() for word in [
        "vote",
        "poll",
        "elect",
        "result",
        "margin",
        "lead",
        "party",
        "candidate"
    ]):
        print("→", col)

Possible vote/result columns:
→ candidate
→ party
→ evm_votes
→ postal_votes
→ total_votes
→ vote_share

In [87]:
# ============================================
# MODULE 19: VOTE ANALYSIS DATASET
# ============================================

vote_analysis = results_clean.copy()

print("Vote analysis dataset created.")
print("Rows   :", vote_analysis.shape[0])
print("Columns:", vote_analysis.shape[1])

Vote analysis dataset created.
Rows   : 8902
Columns: 10

In [88]:
# ============================================
# CHECK REQUIRED VOTE COLUMNS
# ============================================

required_columns = [
    "candidate",
    "party",
    "evm_votes",
    "postal_votes",
    "total_votes",
    "vote_share"
]

print("Required columns:")
for column in required_columns:
    print(column, "→", column in vote_analysis.columns)

Required columns:
candidate → True
party → True
evm_votes → True
postal_votes → True
total_votes → True
vote_share → True

In [96]:
# ============================================
# VOTE DATA VALIDATION
# ============================================

vote_columns = [
    "evm_votes",
    "postal_votes",
    "total_votes",
    "vote_share"
]

for column in vote_columns:
    print(f"\n{column}")
    print("Data type:", vote_analysis[column].dtype)
    print("Missing:", vote_analysis[column].isna().sum())
    print("Negative:", (vote_analysis[column] < 0).sum())

evm_votes
Data type: Int64
Missing: 1
Negative: 0

postal_votes
Data type: Int64
Missing: 578
Negative: 0

total_votes
Data type: Int64
Missing: 1
Negative: 0

vote_share
Data type: Float64
Missing: 1
Negative: 0

In [91]:
# ============================================
# CHECK VOTE COLUMN DATA TYPES
# ============================================

for column in [
    "evm_votes",
    "postal_votes",
    "total_votes",
    "vote_share"
]:
    print(column, "→", vote_analysis[column].dtype)

evm_votes → string
postal_votes → string
total_votes → string
vote_share → string

In [92]:
# ============================================
# CONVERT VOTE COLUMNS TO NUMERIC
# ============================================

vote_columns = [
    "evm_votes",
    "postal_votes",
    "total_votes",
    "vote_share"
]

for column in vote_columns:
    vote_analysis[column] = pd.to_numeric(
        vote_analysis[column],
        errors="coerce"
    )

print("Vote columns converted to numeric.")

Vote columns converted to numeric.

In [93]:
# ============================================
# CHECK MISSING VALUES AFTER CONVERSION
# ============================================

for column in vote_columns:
    print(
        f"{column}:",
        vote_analysis[column].isna().sum(),
        "missing values"
    )

evm_votes: 1 missing values
postal_votes: 578 missing values
total_votes: 1 missing values
vote_share: 1 missing values

In [94]:
# ============================================
# VOTE STATISTICS
# ============================================

display(
    vote_analysis[
        [
            "evm_votes",
            "postal_votes",
            "total_votes",
            "vote_share"
        ]
    ].describe()
)

           evm_votes  postal_votes    total_votes  vote_share
count         8901.0        8324.0         8901.0      8901.0
mean    72083.916077    449.844786   72504.600045    6.089172
std    178879.674654   1380.591598  179907.238636   14.630761
min             58.0           1.0           61.0        0.01
25%           1085.0           4.0         1095.0        0.09
50%           2769.0          11.0         2781.0        0.24
75%           9681.0          59.0         9763.0        0.81
max        1468549.0       19827.0      1471885.0       78.54

In [95]:
# ============================================
# VERIFY TOTAL VOTES
# ============================================

vote_analysis["calculated_total_votes"] = (
    vote_analysis["evm_votes"].fillna(0)
    + vote_analysis["postal_votes"].fillna(0)
)

vote_analysis["vote_difference"] = (
    vote_analysis["total_votes"]
    - vote_analysis["calculated_total_votes"]
)

print(
    "Rows where calculated votes differ:",
    (vote_analysis["vote_difference"] != 0).sum()
)

Rows where calculated votes differ: 0

In [97]:
# ============================================
# MODULE 20: VERIFY TOTAL VOTES
# ============================================

vote_analysis["calculated_total_votes"] = (
    vote_analysis["evm_votes"].fillna(0)
    + vote_analysis["postal_votes"].fillna(0)
)

vote_analysis["vote_difference"] = (
    vote_analysis["total_votes"]
    - vote_analysis["calculated_total_votes"]
)

print(
    "Rows where calculated votes differ:",
    (vote_analysis["vote_difference"] != 0).sum()
)

print(
    "Rows with missing total votes:",
    vote_analysis["total_votes"].isna().sum()
)

Rows where calculated votes differ: 0
Rows with missing total votes: 1

In [98]:
# ============================================
# SHOW VOTE MISMATCHES
# ============================================

mismatches = vote_analysis[
    vote_analysis["vote_difference"] != 0
]

print("Mismatch rows:", len(mismatches))

display(
    mismatches[
        [
            "candidate",
            "party",
            "evm_votes",
            "postal_votes",
            "total_votes",
            "calculated_total_votes",
            "vote_difference"
        ]
    ].head(20)
)

Mismatch rows: 0

Empty DataFrame
Columns: [candidate, party, evm_votes, postal_votes, total_votes, calculated_total_votes, vote_difference]
Index: []

In [99]:
# ============================================
# MODULE 21: LOCATION COLUMNS
# ============================================

print("State-related columns:")

for col in vote_analysis.columns:
    if "state" in col.lower():
        print("→", col)

print("\nConstituency-related columns:")

for col in vote_analysis.columns:
    if any(word in col.lower() for word in [
        "constituency",
        "pc_name",
        "pc_no"
    ]):
        print("→", col)

State-related columns:
→ state

Constituency-related columns:
→ pc_no
→ pc_name

In [100]:
state_col = "state"
constituency_col = "constituency"

In [101]:
# ============================================
# RECTIFY LOCATION COLUMNS
# ============================================

print("Vote analysis columns:")
print(vote_analysis.columns.tolist())

Vote analysis columns:
['state', 'pc_no', 'pc_name', 'sl_no', 'candidate', 'party', 'evm_votes', 'postal_votes', 'total_votes', 'vote_share', 'calculated_total_votes', 'vote_difference']

In [102]:
# ============================================
# FIND LOCATION COLUMNS AUTOMATICALLY
# ============================================

state_candidates = [
    col for col in vote_analysis.columns
    if "state" in col.lower()
]

constituency_candidates = [
    col for col in vote_analysis.columns
    if "constituency" in col.lower()
    or "pc_name" in col.lower()
]

print("State candidates:", state_candidates)
print("Constituency candidates:", constituency_candidates)

State candidates: ['state']
Constituency candidates: ['pc_name']

In [103]:
state_col = "state"
constituency_col = "pc_name"

print("State column:", state_col)
print("Constituency column:", constituency_col)

State column: state
Constituency column: pc_name

In [104]:
# ============================================
# MODULE 23: CONSTITUENCY TOTAL VOTES
# ============================================

vote_analysis["constituency_total_votes"] = (
    vote_analysis
    .groupby(
        [state_col, constituency_col]
    )["total_votes"]
    .transform("sum")
)

display(
    vote_analysis[
        [
            state_col,
            constituency_col,
            "candidate",
            "party",
            "total_votes",
            "constituency_total_votes"
        ]
    ].head(10)
)

,state,pc_name,candidate,party,total_votes,constituency_total_votes
0,Andhra Pradesh,Araku (ST),GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,477005,1164445
1,Andhra Pradesh,Araku (ST),KOTHAPALLI GEETHA,Bharatiya Janata Party,426425,1164445
2,Andhra Pradesh,Araku (ST),APPALANARASA PACHIPENTA,Communist Party of India (Marxist),123129,1164445
3,Andhra Pradesh,Araku (ST),AVASHYA LAHARI . VARAM,Bahujan Samaj Party,25750,1164445
4,Andhra Pradesh,Araku (ST),SAMAREDDY BALAKRISHNA,Independent,9535,1164445
5,Andhra Pradesh,Araku (ST),NIMMAKA JAYARAJU,Independent,9462,1164445
6,Andhra Pradesh,Araku (ST),ATHIDHI,Independent,8136,1164445
7,Andhra Pradesh,Araku (ST),CHANTI BADNAINA,Jai Bharat National Party,7252,1164445
8,Andhra Pradesh,Araku (ST),MOTTADAM . RAJABABU,Bharat Adivasi Party,6766,1164445
9,Andhra Pradesh,Araku (ST),RANJITH KUMAR PALAKA,Independent,6047,1164445

In [106]:
# ============================================
# MODULE 24: CALCULATE VOTE SHARE
# ============================================

vote_analysis["calculated_vote_share"] = (
    vote_analysis["total_votes"]
    / vote_analysis["constituency_total_votes"]
) * 100

vote_analysis["calculated_vote_share"] = (
    vote_analysis["calculated_vote_share"].round(2)
)

display(
    vote_analysis[
        [
            "candidate",
            "party",
            "total_votes",
            "vote_share",
            "calculated_vote_share"
        ]
    ].head(10)
)

                 candidate                                  party  total_votes  vote_share  calculated_vote_share
0       GUMMA THANUJA RANI  Yuvajana Sramika Rythu Congress Party       477005       40.96                  40.96
1        KOTHAPALLI GEETHA                 Bharatiya Janata Party       426425       36.62                  36.62
2  APPALANARASA PACHIPENTA    Communist Party of India  (Marxist)       123129       10.57                  10.57
3   AVASHYA LAHARI . VARAM                    Bahujan Samaj Party        25750        2.21                   2.21
4    SAMAREDDY BALAKRISHNA                            Independent         9535        0.82                   0.82
5         NIMMAKA JAYARAJU                            Independent         9462        0.81                   0.81
6                  ATHIDHI                            Independent         8136         0.7                    0.7
7          CHANTI BADNAINA              Jai Bharat National Party         7252        0.62                   0.62
8      MOTTADAM . RAJABABU                   Bharat Adivasi Party         6766        0.58                   0.58
9     RANJITH KUMAR PALAKA                            Independent         6047        0.52                   0.52

In [107]:
# ============================================
# MODULE 25: VALIDATE VOTE SHARE
# ============================================

vote_analysis["vote_share_difference"] = (
    vote_analysis["vote_share"]
    - vote_analysis["calculated_vote_share"]
)

print(
    "Average absolute difference:",
    vote_analysis["vote_share_difference"].abs().mean()
)

print(
    "Maximum absolute difference:",
    vote_analysis["vote_share_difference"].abs().max()
)

Average absolute difference: 0.0
Maximum absolute difference: 0.0

In [108]:
# ============================================
# MODULE 26: IDENTIFY WINNERS
# ============================================

max_votes = (
    vote_analysis
    .groupby(
        [state_col, constituency_col]
    )["total_votes"]
    .transform("max")
)

vote_analysis["is_winner"] = (
    vote_analysis["total_votes"] == max_votes
)

print(
    "Winner records:",
    vote_analysis["is_winner"].sum()
)

Winner records: 542

In [109]:
# ============================================
# MODULE 27: WINNING MARGIN
# ============================================

def calculate_winning_margin(group):

    sorted_votes = (
        group["total_votes"]
        .sort_values(ascending=False)
        .values
    )

    if len(sorted_votes) >= 2:
        return sorted_votes[0] - sorted_votes[1]

    return np.nan


margin_df = (
    vote_analysis
    .groupby([state_col, constituency_col])
    .apply(calculate_winning_margin)
    .reset_index(name="winning_margin")
)

display(margin_df.head(10))

                       state                    pc_name  winning_margin
0  Andaman & Nicobar Islands  Andaman & Nicobar Islands         24396.0
1             Andhra Pradesh            Amalapuram (SC)        342196.0
2             Andhra Pradesh                 Anakapalle        296530.0
3             Andhra Pradesh                 Ananthapur        188555.0
4             Andhra Pradesh                 Araku (ST)         50580.0
5             Andhra Pradesh               Bapatla (SC)        208031.0
6             Andhra Pradesh               Chittoor(SC)        220479.0
7             Andhra Pradesh                      Eluru        181857.0
8             Andhra Pradesh                     Guntur        344695.0
9             Andhra Pradesh                   Hindupur        132427.0

In [110]:
# ============================================
# MODULE 28: ADD WINNING MARGIN
# ============================================

vote_analysis = vote_analysis.merge(
    margin_df,
    on=[state_col, constituency_col],
    how="left"
)

display(
    vote_analysis[
        [
            state_col,
            constituency_col,
            "candidate",
            "party",
            "total_votes",
            "vote_share",
            "is_winner",
            "winning_margin"
        ]
    ].head(53)
)

,state,pc_name,candidate,party,total_votes,vote_share,is_winner,winning_margin
0,Andhra Pradesh,Araku (ST),GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,477005,40.96,True,50580.0
1,Andhra Pradesh,Araku (ST),KOTHAPALLI GEETHA,Bharatiya Janata Party,426425,36.62,False,50580.0
2,Andhra Pradesh,Araku (ST),APPALANARASA PACHIPENTA,Communist Party of India (Marxist),123129,10.57,False,50580.0
3,Andhra Pradesh,Araku (ST),AVASHYA LAHARI . VARAM,Bahujan Samaj Party,25750,2.21,False,50580.0
4,Andhra Pradesh,Araku (ST),SAMAREDDY BALAKRISHNA,Independent,9535,0.82,False,50580.0
5,Andhra Pradesh,Araku (ST),NIMMAKA JAYARAJU,Independent,9462,0.81,False,50580.0
6,Andhra Pradesh,Araku (ST),ATHIDHI,Independent,8136,0.7,False,50580.0
7,Andhra Pradesh,Araku (ST),CHANTI BADNAINA,Jai Bharat National Party,7252,0.62,False,50580.0
8,Andhra Pradesh,Araku (ST),MOTTADAM . RAJABABU,Bharat Adivasi Party,6766,0.58,False,50580.0
9,Andhra Pradesh,Araku (ST),RANJITH KUMAR PALAKA,Independent,6047,0.52,False,50580.0
10,Andhra Pradesh,Araku (ST),RAMBABU JALLI,Telugu Rajadhikara Samiti Party,4959,0.43,False,50580.0
11,Andhra Pradesh,Araku (ST),MANDALA GIRIDHARA RAO,Independent,4967,0.43,False,50580.0
12,Andhra Pradesh,Araku (ST),VUYAKA NIREEKSHAN (V. CHENCHU),India Praja Bandhu Party,4542,0.39,False,50580.0
13,Andhra Pradesh,Araku (ST),NOTA,None of the Above,50470,4.33,False,50580.0
14,Andhra Pradesh,Srikakulam,KINJARAPU RAMMOHAN NAIDU,Telugu Desam,754328,61.05,True,327901.0
15,Andhra Pradesh,Srikakulam,TILAK PERADA,Yuvajana Sramika Rythu Congress Party,426427,34.51,False,327901.0
16,Andhra Pradesh,Srikakulam,PEDADA PARAMESWARA RAO,Indian National Congress,7172,0.58,False,327901.0
17,Andhra Pradesh,Srikakulam,SANAPALA SRAVAN KUMAR,Independent,5958,0.48,False,327901.0
18,Andhra Pradesh,Srikakulam,NAIDUGARI RAJASEKHAR,Bahujan Samaj Party,4742,0.38,False,327901.0
19,Andhra Pradesh,Srikakulam,VABA YOGESWARA RAO,Independent,3598,0.29,False,327901.0
20,Andhra Pradesh,Srikakulam,BETHA VIVEKANANDA MAHARAJ,Independent,2536,0.21,False,327901.0
21,Andhra Pradesh,Srikakulam,YEDDU LAKSHMINARAYANA,Independent,1605,0.13,False,327901.0
22,Andhra Pradesh,Srikakulam,BORUBADRA CHANDRAKALA,Bharatha Chaitanya Yuvajana Party,1357,0.11,False,327901.0
23,Andhra Pradesh,Srikakulam,IPPILI SEETHARAJU,Jai Bharat National Party,1130,0.09,False,327901.0
24,Andhra Pradesh,Srikakulam,KAYA DURGARAO,Navarang Congress Party,818,0.07,False,327901.0
25,Andhra Pradesh,Srikakulam,CHELLURI DANIYAL,Independent,816,0.07,False,327901.0
26,Andhra Pradesh,Srikakulam,BOMMALI TIRUPATI RAO,Pyramid Party of India,594,0.05,False,327901.0
27,Andhra Pradesh,Srikakulam,NOTA,None of the Above,24605,1.99,False,327901.0
28,Andhra Pradesh,Vizianagaram,APPALANAIDU KALISETTI,Telugu Desam,743113,57.2,True,249351.0
29,Andhra Pradesh,Vizianagaram,BELLANA CHANDRASEKHAR,Yuvajana Sramika Rythu Congress Party,493762,38.0,False,249351.0
30,Andhra Pradesh,Vizianagaram,BOBBILI SRINU,Indian National Congress,10623,0.82,False,249351.0
31,Andhra Pradesh,Vizianagaram,PEERUBANDI PRAKASH RAO,Bahujan Samaj Party,8038,0.62,False,249351.0
32,Andhra Pradesh,Vizianagaram,VELURI VENKATA TRINADHARAO,Independent,4152,0.32,False,249351.0
33,Andhra Pradesh,Vizianagaram,ALLU SRIRAMULU,Independent,3401,0.26,False,249351.0
34,Andhra Pradesh,Vizianagaram,SIYYADULA YELLA RAO,Independent,3107,0.24,False,249351.0
35,Andhra Pradesh,Vizianagaram,SRINIVASA RAO SAMBHANA,Yuga Thulasi Party,1761,0.14,False,249351.0
36,Andhra Pradesh,Vizianagaram,MARISERLA KRISHNAMURTHY NAIDU,Independent,1629,0.13,False,249351.0
37,Andhra Pradesh,Vizianagaram,VANGAPANDU MAHESWARA RAO,Naba Bharata Nirmana Seva Party,1553,0.12,False,249351.0
38,Andhra Pradesh,Vizianagaram,CHINNAM ARUNA KUMAR,Jaibhim Rao Bharat Party,1411,0.11,False,249351.0
39,Andhra Pradesh,Vizianagaram,ATCHIYYA NAIDU SAMIREDDY,Samajwadi Party,1070,0.08,False,249351.0
40,Andhra Pradesh,Vizianagaram,ADINARAYANA TADDI,Independent,856,0.07,False,249351.0
41,Andhra Pradesh,Vizianagaram,P V A ANANDA SAGAR,Independent,791,0.06,False,249351.0
42,Andhra Pradesh,Vizianagaram,SAKHINETI ANANTHA RAJU,Pyramid Party of India,725,0.06,False,249351.0
43,Andhra Pradesh,Vizianagaram,NOTA,None of the Above,23250,1.79,False,249351.0
44,Andhra Pradesh,Visakhapatnam,SRIBHARAT MATHUKUMILI,Telugu Desam,907467,65.42,True,504247.0
45,Andhra Pradesh,Visakhapatnam,JHANSI LAKSHMI. BOTCHA.,Yuvajana Sramika Rythu Congress Party,403220,29.07,False,504247.0
46,Andhra Pradesh,Visakhapatnam,P. SATYA REDDY,Indian National Congress,30267,2.18,False,504247.0
47,Andhra Pradesh,Visakhapatnam,K.A. PAUL,Praja Shanthi Party,7696,0.55,False,504247.0
48,Andhra Pradesh,Visakhapatnam,PEDAPENKI SIVA PRASADA RAO,Bahujan Samaj Party,6091,0.44,False,504247.0
49,Andhra Pradesh,Visakhapatnam,BIKKAVOLU. CHALAMAJI,Navarang Congress Party,4884,0.35,False,504247.0
50,Andhra Pradesh,Visakhapatnam,V.N. SATYA NARAYANA,Rashtriya Praja Congress (Secular),2537,0.18,False,504247.0
51,Andhra Pradesh,Visakhapatnam,ARUNA SRI MURALA,Independent,1993,0.14,False,504247.0
52,Andhra Pradesh,Visakhapatnam,VASUPILLI SURESH,Independent,1933,0.14,False,504247.0

In [111]:
# ============================================
# MODULE 29: FIND ELECTOR / TURNOUT DATA
# ============================================

print("Elector / turnout related columns:")

for col in results_clean.columns:
    if any(word in col.lower() for word in [
        "elector",
        "turnout",
        "poll",
        "voter"
    ]):
        print("→", col)

Elector / turnout related columns:

In [112]:
# ============================================
# CHECK RESULTS COLUMNS
# ============================================

print(results_clean.columns.tolist())

['state', 'pc_no', 'pc_name', 'sl_no', 'candidate', 'party', 'evm_votes', 'postal_votes', 'total_votes', 'vote_share']

In [113]:
# ============================================
# MODULE 30.1: FIND HISTORICAL LOK SABHA CSV
# ============================================

from pathlib import Path

print("CSV files available in raw data folder:")

for file in RAW_DATA.glob("*.csv"):
    print("→", file.name)

CSV files available in raw data folder:

In [115]:
# ============================================
# MODULE 30.1: LOAD HISTORICAL LOK SABHA DATA
# ============================================

historical_file = RAW_DATA / "historical" / "ind-lok-sabha.csv"

lok_sabha = pd.read_csv(historical_file)

print("Historical Lok Sabha dataset loaded successfully.")
print("Rows:", lok_sabha.shape[0])
print("Columns:", lok_sabha.shape[1])

display(lok_sabha.head())

Historical Lok Sabha dataset loaded successfully.
Rows: 73081
Columns: 11

,st_name,year,pc_no,pc_name,pc_type,cand_name,cand_sex,partyname,partyabbre,totvotpoll,electors
0,Andaman & Nicobar Islands,1977,1,Andaman & Nicobar Islands,GEN,K.R. Ganesh,M,Independents,IND,25168,85308
1,Andaman & Nicobar Islands,1977,1,Andaman & Nicobar Islands,GEN,Manoranjan Bhakta,M,Indian National Congress,INC,35400,85308
2,Andaman & Nicobar Islands,1980,1,Andaman & Nicobar Islands,GEN,Ramesh Mazumdar,M,Independents,IND,109,96084
3,Andaman & Nicobar Islands,1980,1,Andaman & Nicobar Islands,GEN,Alagiri Swamy,M,Independents,IND,125,96084
4,Andaman & Nicobar Islands,1980,1,Andaman & Nicobar Islands,GEN,Kannu Chemy,M,Independents,IND,405,96084

In [116]:
# ============================================
# MODULE 30.2: INSPECT HISTORICAL DATA
# ============================================

print("Columns:")
print(lok_sabha.columns.tolist())

print("\nData types:")
print(lok_sabha.dtypes)

Columns:
['st_name', 'year', 'pc_no', 'pc_name', 'pc_type', 'cand_name', 'cand_sex', 'partyname', 'partyabbre', 'totvotpoll', 'electors']

Data types:
st_name         str
year          int64
pc_no         int64
pc_name         str
pc_type         str
cand_name       str
cand_sex        str
partyname       str
partyabbre      str
totvotpoll    int64
electors      int64
dtype: object

In [117]:
# ============================================
# MODULE 30.3: AVAILABLE ELECTION YEARS
# ============================================

years = sorted(
    lok_sabha["year"]
    .dropna()
    .unique()
)

print("Available Lok Sabha election years:")
print(years)

print("\nLatest year:", max(years))

Available Lok Sabha election years:
[np.int64(1977), np.int64(1980), np.int64(1984), np.int64(1989), np.int64(1991), np.int64(1996), np.int64(1998), np.int64(1999), np.int64(2004), np.int64(2009), np.int64(2014)]

Latest year: 2014

In [118]:
# ============================================
# MODULE 30.4: CLEAN HISTORICAL DATA
# ============================================

historical_lok_sabha = lok_sabha.copy()

# Remove duplicate rows
historical_lok_sabha = (
    historical_lok_sabha
    .drop_duplicates()
    .reset_index(drop=True)
)

# Convert numeric columns
historical_lok_sabha["year"] = pd.to_numeric(
    historical_lok_sabha["year"],
    errors="coerce"
)

historical_lok_sabha["totvotpoll"] = pd.to_numeric(
    historical_lok_sabha["totvotpoll"],
    errors="coerce"
)

historical_lok_sabha["electors"] = pd.to_numeric(
    historical_lok_sabha["electors"],
    errors="coerce"
)

print("Historical data cleaned.")
print("Rows:", len(historical_lok_sabha))

Historical data cleaned.
Rows: 73080

In [119]:
# ============================================
# MODULE 31: CONSTITUENCY-LEVEL HISTORICAL DATA
# ============================================

historical_constituency = (
    historical_lok_sabha
    .groupby(
        [
            "st_name",
            "year",
            "pc_no",
            "pc_name"
        ],
        as_index=False
    )
    .agg(
        total_votes=("totvotpoll", "sum"),
        electors=("electors", "first")
    )
)

print("Historical constituency records:",
      len(historical_constituency))

display(historical_constituency.head(10))

Historical constituency records: 5934

                     st_name  year  pc_no                    pc_name  total_votes  electors
0  Andaman & Nicobar Islands  1977      1  Andaman & Nicobar Islands        60568     85308
1  Andaman & Nicobar Islands  1980      1  Andaman & Nicobar Islands        78899     96084
2  Andaman & Nicobar Islands  1984      1  Andaman & Nicobar Islands        88968    115565
3  Andaman & Nicobar Islands  1989      1  Andaman & Nicobar Islands       113065    160940
4  Andaman & Nicobar Islands  1991      1  Andaman & Nicobar Islands       107316    169120
5  Andaman & Nicobar Islands  1996      1  Andaman & Nicobar Islands       128212    211226
6  Andaman & Nicobar Islands  1998      1  Andaman & Nicobar Islands       145836    232013
7  Andaman & Nicobar Islands  1999      1  Andaman & Nicobar Islands       145791    247384
8  Andaman & Nicobar Islands  2004      1  Andaman & Nicobar Islands       153825    241645
9  Andaman & Nicobar Islands  2009      1  Andaman & Nicobar Islands       170103    265110

In [120]:
# ============================================
# MODULE 32: HISTORICAL TURNOUT
# ============================================

historical_constituency["turnout_percentage"] = (
    historical_constituency["total_votes"]
    / historical_constituency["electors"]
) * 100

historical_constituency["turnout_percentage"] = (
    historical_constituency["turnout_percentage"]
    .round(2)
)

display(
    historical_constituency[
        [
            "st_name",
            "year",
            "pc_name",
            "total_votes",
            "electors",
            "turnout_percentage"
        ]
    ].head(10)
)

                     st_name  year                    pc_name  total_votes  electors  turnout_percentage
0  Andaman & Nicobar Islands  1977  Andaman & Nicobar Islands        60568     85308               71.00
1  Andaman & Nicobar Islands  1980  Andaman & Nicobar Islands        78899     96084               82.11
2  Andaman & Nicobar Islands  1984  Andaman & Nicobar Islands        88968    115565               76.99
3  Andaman & Nicobar Islands  1989  Andaman & Nicobar Islands       113065    160940               70.25
4  Andaman & Nicobar Islands  1991  Andaman & Nicobar Islands       107316    169120               63.46
5  Andaman & Nicobar Islands  1996  Andaman & Nicobar Islands       128212    211226               60.70
6  Andaman & Nicobar Islands  1998  Andaman & Nicobar Islands       145836    232013               62.86
7  Andaman & Nicobar Islands  1999  Andaman & Nicobar Islands       145791    247384               58.93
8  Andaman & Nicobar Islands  2004  Andaman & Nicobar Islands       153825    241645               63.66
9  Andaman & Nicobar Islands  2009  Andaman & Nicobar Islands       170103    265110               64.16

In [121]:
# ============================================
# MODULE 33: NATIONAL TURNOUT TREND
# ============================================

national_turnout_history = (
    historical_constituency
    .groupby("year")
    .agg(
        total_votes=("total_votes", "sum"),
        total_electors=("electors", "sum")
    )
    .reset_index()
)

national_turnout_history["turnout_percentage"] = (
    national_turnout_history["total_votes"]
    / national_turnout_history["total_electors"]
) * 100

national_turnout_history["turnout_percentage"] = (
    national_turnout_history["turnout_percentage"]
    .round(2)
)

display(national_turnout_history)

    year  total_votes  total_electors  turnout_percentage
0   1977    188917504       321174327               58.82
1   1980    197824274       356205329               55.54
2   1984    249583543       400375333               62.34
3   1989    300713805       498906129               60.27
4   1991    278218849       511533598               54.39
5   1996    334327592       592572288               56.42
6   1998    367952396       605880192               60.73
7   1999    363694693       619536847               58.70
8   2004    389779784       671487930               58.05
9   2009    417158672       716676063               58.21
10  2014    553802946       834082814               66.40

In [122]:
# ============================================
# MODULE 33: NATIONAL TURNOUT TREND
# ============================================

national_turnout_history = (
    historical_constituency
    .groupby("year")
    .agg(
        total_votes=("total_votes", "sum"),
        total_electors=("electors", "sum")
    )
    .reset_index()
)

national_turnout_history["turnout_percentage"] = (
    national_turnout_history["total_votes"]
    / national_turnout_history["total_electors"]
) * 100

national_turnout_history["turnout_percentage"] = (
    national_turnout_history["turnout_percentage"]
    .round(2)
)

display(national_turnout_history)

    year  total_votes  total_electors  turnout_percentage
0   1977    188917504       321174327               58.82
1   1980    197824274       356205329               55.54
2   1984    249583543       400375333               62.34
3   1989    300713805       498906129               60.27
4   1991    278218849       511533598               54.39
5   1996    334327592       592572288               56.42
6   1998    367952396       605880192               60.73
7   1999    363694693       619536847               58.70
8   2004    389779784       671487930               58.05
9   2009    417158672       716676063               58.21
10  2014    553802946       834082814               66.40

In [123]:
# ============================================
# MODULE 34: STATE-WISE HISTORICAL TURNOUT
# ============================================

state_turnout_history = (
    historical_constituency
    .groupby(
        ["st_name", "year"]
    )
    .agg(
        total_votes=("total_votes", "sum"),
        total_electors=("electors", "sum")
    )
    .reset_index()
)

state_turnout_history["turnout_percentage"] = (
    state_turnout_history["total_votes"]
    / state_turnout_history["total_electors"]
) * 100

state_turnout_history["turnout_percentage"] = (
    state_turnout_history["turnout_percentage"]
    .round(2)
)

display(state_turnout_history.head(20))

                      st_name  year  total_votes  total_electors  turnout_percentage
0   Andaman & Nicobar Islands  1977        60568           85308               71.00
1   Andaman & Nicobar Islands  1980        78899           96084               82.11
2   Andaman & Nicobar Islands  1984        88968          115565               76.99
3   Andaman & Nicobar Islands  1989       113065          160940               70.25
4   Andaman & Nicobar Islands  1991       107316          169120               63.46
5   Andaman & Nicobar Islands  1996       128212          211226               60.70
6   Andaman & Nicobar Islands  1998       145836          232013               62.86
7   Andaman & Nicobar Islands  1999       145791          247384               58.93
8   Andaman & Nicobar Islands  2004       153825          241645               63.66
9   Andaman & Nicobar Islands  2009       170103          265110               64.16
10  Andaman & Nicobar Islands  2014       190328          269360               70.66
11             Andhra Pradesh  1977     16705123        27567618               60.60
12             Andhra Pradesh  1980     16907792        30497603               55.44
13             Andhra Pradesh  1984     22609046        33546487               67.40
14             Andhra Pradesh  1989     28764919        42475179               67.72
15             Andhra Pradesh  1991     25488643        42617973               59.81
16             Andhra Pradesh  1996     30474862        49501274               61.56
17             Andhra Pradesh  1998     31898911        49133135               64.92
18             Andhra Pradesh  1999     33365484        49654389               67.20
19             Andhra Pradesh  2004     35762670        51146342               69.92

In [124]:
# ============================================
# MODULE 35: NATIONAL PARTY SEATS
# ============================================

national_party_results = (
    vote_analysis[
        vote_analysis["is_winner"] == True
    ]
    .groupby("party")
    .size()
    .reset_index(name="seats_won")
    .sort_values(
        "seats_won",
        ascending=False
    )
)

display(national_party_results.head(20))

                                                party  seats_won
8                              Bharatiya Janata Party        239
15                           Indian National Congress         99
31                                    Samajwadi Party         37
4                        All India Trinamool Congress         29
12                          Dravida Munnetra Kazhagam         22
36                                       Telugu Desam         16
20                               Janata Dal  (United)         12
34              Shiv Sena (Uddhav Balasaheb Thackrey)          9
26   Nationalist Congress Party – Sharadchandra Pawar          8
14                                        Independent          7
33                                          Shiv Sena          7
23                     Lok Janshakti Party(Ram Vilas)          5
40              Yuvajana Sramika Rythu Congress Party          4
27                               Rashtriya Janata Dal          4
10                Communist Party of India  (Marxist)          4
16                         Indian Union Muslim League          3
21                             Jharkhand Mukti Morcha          3
1                                     Aam Aadmi Party          3
38                     Viduthalai Chiruthaigal Katchi          2
11  Communist Party of India  (Marxist-Leninist)  ...          2

In [125]:
# ============================================
# MODULE 36: STATE-WISE PARTY SEATS
# ============================================

state_party_results = (
    vote_analysis[
        vote_analysis["is_winner"] == True
    ]
    .groupby(
        ["state", "party"]
    )
    .size()
    .reset_index(name="seats_won")
    .sort_values(
        ["state", "seats_won"],
        ascending=[True, False]
    )
)

display(state_party_results.head(30))

                                   state                                              party  seats_won
0              Andaman & Nicobar Islands                             Bharatiya Janata Party          1
3                         Andhra Pradesh                                       Telugu Desam         16
4                         Andhra Pradesh              Yuvajana Sramika Rythu Congress Party          4
1                         Andhra Pradesh                             Bharatiya Janata Party          3
2                         Andhra Pradesh                                     Janasena Party          2
5                      Arunachal Pradesh                             Bharatiya Janata Party          2
7                                  Assam                             Bharatiya Janata Party          9
8                                  Assam                           Indian National Congress          3
6                                  Assam                                 Asom Gana Parishad          1
9                                  Assam                     United People’s Party, Liberal          1
10                                 Bihar                             Bharatiya Janata Party         12
15                                 Bihar                               Janata Dal  (United)         12
16                                 Bihar                     Lok Janshakti Party(Ram Vilas)          5
17                                 Bihar                               Rashtriya Janata Dal          4
14                                 Bihar                           Indian National Congress          3
11                                 Bihar  Communist Party of India  (Marxist-Leninist)  ...          2
12                                 Bihar                   Hindustani Awam Morcha (Secular)          1
13                                 Bihar                                        Independent          1
18                            Chandigarh                           Indian National Congress          1
19                          Chhattisgarh                             Bharatiya Janata Party         10
20                          Chhattisgarh                           Indian National Congress          1
21  Dadra & Nagar Haveli and Daman & Diu                             Bharatiya Janata Party          1
22  Dadra & Nagar Haveli and Daman & Diu                                        Independent          1
23                                   Goa                             Bharatiya Janata Party          1
24                                   Goa                           Indian National Congress          1
25                               Gujarat                             Bharatiya Janata Party         24
26                               Gujarat                           Indian National Congress          1
27                               Haryana                             Bharatiya Janata Party          5
28                               Haryana                           Indian National Congress          5
29                      Himachal Pradesh                             Bharatiya Janata Party          4

In [126]:
# ============================================
# MODULE 37: NATIONAL PARTY VOTE SHARE
# ============================================

party_votes = (
    vote_analysis
    .groupby("party")["total_votes"]
    .sum()
    .reset_index(name="total_votes")
    .sort_values(
        "total_votes",
        ascending=False
    )
)

total_national_votes = party_votes["total_votes"].sum()

party_votes["national_vote_share"] = (
    party_votes["total_votes"]
    / total_national_votes
) * 100

party_votes["national_vote_share"] = (
    party_votes["national_vote_share"]
    .round(2)
)

display(party_votes.head(20))

                                                party  total_votes  national_vote_share
158                            Bharatiya Janata Party    235973935                36.56
289                          Indian National Congress    136759064                21.19
617                                   Samajwadi Party     29549381                 4.58
69                       All India Trinamool Congress     28213393                 4.37
282                                       Independent     17844442                 2.77
744             Yuvajana Sramika Rythu Congress Party     13316039                 2.06
121                               Bahujan Samaj Party     13153818                 2.04
698                                      Telugu Desam     12775270                 1.98
250                         Dravida Munnetra Kazhagam     11754710                 1.82
227               Communist Party of India  (Marxist)     11342553                 1.76
539                              Rashtriya Janata Dal     10107402                 1.57
657             Shiv Sena (Uddhav Balasaheb Thackrey)      9567779                 1.48
217                                   Biju Janata Dal      9413379                 1.46
55           All India Anna Dravida Munnetra Kazhagam      8952587                 1.39
333                              Janata Dal  (United)      8039663                 1.25
656                                         Shiv Sena      7401447                 1.15
7                                     Aam Aadmi Party      7147800                 1.11
471                                 None of the Above      6372220                 0.99
455  Nationalist Congress Party – Sharadchandra Pawar      5921162                 0.92
142                            Bharat Rashtra Samithi      3657237                 0.57

In [127]:
# ============================================
# MODULE 38: FINAL 2024 CONSTITUENCY RESULTS
# ============================================

constituency_results_2024 = (
    vote_analysis[
        vote_analysis["is_winner"] == True
    ][
        [
            "state",
            "pc_no",
            "pc_name",
            "candidate",
            "party",
            "total_votes",
            "vote_share",
            "winning_margin"
        ]
    ]
    .copy()
    .reset_index(drop=True)
)

print("2024 Constituency Results")
print("Rows:", len(constituency_results_2024))
print("Columns:", constituency_results_2024.columns.tolist())

display(constituency_results_2024.head(10))

2024 Constituency Results
Rows: 542
Columns: ['state', 'pc_no', 'pc_name', 'candidate', 'party', 'total_votes', 'vote_share', 'winning_margin']

,state,pc_no,pc_name,candidate,party,total_votes,vote_share,winning_margin
0,Andhra Pradesh,1,Araku (ST),GUMMA THANUJA RANI,Yuvajana Sramika Rythu Congress Party,477005,40.96,50580.0
1,Andhra Pradesh,2,Srikakulam,KINJARAPU RAMMOHAN NAIDU,Telugu Desam,754328,61.05,327901.0
2,Andhra Pradesh,3,Vizianagaram,APPALANAIDU KALISETTI,Telugu Desam,743113,57.2,249351.0
3,Andhra Pradesh,4,Visakhapatnam,SRIBHARAT MATHUKUMILI,Telugu Desam,907467,65.42,504247.0
4,Andhra Pradesh,5,Anakapalle,C.M.RAMESH,Bharatiya Janata Party,762069,57.5,296530.0
5,Andhra Pradesh,6,Kakinada,TANGELLA UDAY SRINIVAS (TEA TIME UDAY),Janasena Party,729699,54.87,229491.0
6,Andhra Pradesh,7,Amalapuram (SC),G M HARISH (BALAYOGI),Telugu Desam,796981,61.25,342196.0
7,Andhra Pradesh,8,Rajahmundry,DAGGUBATI PURANDHESHWARI,Bharatiya Janata Party,726515,54.82,239139.0
8,Andhra Pradesh,9,Narsapuram,BHUPATHI RAJU SRINIVASA VARMA (B.J.P.VARMA),Bharatiya Janata Party,707343,57.46,276802.0
9,Andhra Pradesh,10,Eluru,PUTTA MAHESH KUMAR,Telugu Desam,746351,54.0,181857.0

In [128]:
# ============================================
# MODULE 39: FINAL STATE RESULTS
# ============================================

state_results_2024 = (
    constituency_results_2024
    .groupby(["state", "party"])
    .agg(
        seats_won=("pc_name", "count"),
        total_votes=("total_votes", "sum")
    )
    .reset_index()
    .sort_values(
        ["state", "seats_won"],
        ascending=[True, False]
    )
)

display(state_results_2024.head(30))

                                   state                                              party  seats_won  total_votes
0              Andaman & Nicobar Islands                             Bharatiya Janata Party          1       102436
3                         Andhra Pradesh                                       Telugu Desam         16     12232822
4                         Andhra Pradesh              Yuvajana Sramika Rythu Congress Party          4      2359220
1                         Andhra Pradesh                             Bharatiya Janata Party          3      2195927
2                         Andhra Pradesh                                     Janasena Party          2      1454138
5                      Arunachal Pradesh                             Bharatiya Janata Party          2       350998
7                                  Assam                             Bharatiya Janata Party          9      6325107
8                                  Assam                           Indian National Congress          3      3012506
6                                  Assam                                 Asom Gana Parishad          1       860113
9                                  Assam                     United People’s Party, Liberal          1       488995
10                                 Bihar                             Bharatiya Janata Party         12      6628026
15                                 Bihar                               Janata Dal  (United)         12      6335123
16                                 Bihar                     Lok Janshakti Party(Ram Vilas)          5      2810250
17                                 Bihar                               Rashtriya Janata Dal          4      1960230
14                                 Bihar                           Indian National Congress          3      1482946
11                                 Bihar  Communist Party of India  (Marxist-Leninist)  ...          2       909963
12                                 Bihar                   Hindustani Awam Morcha (Secular)          1       494960
13                                 Bihar                                        Independent          1       567556
18                            Chandigarh                           Indian National Congress          1       216657
19                          Chhattisgarh                             Bharatiya Janata Party         10      7403197
20                          Chhattisgarh                           Indian National Congress          1       570182
21  Dadra & Nagar Haveli and Daman & Diu                             Bharatiya Janata Party          1       121074
22  Dadra & Nagar Haveli and Daman & Diu                                        Independent          1        42523
23                                   Goa                             Bharatiya Janata Party          1       257326
24                                   Goa                           Indian National Congress          1       217836
25                               Gujarat                             Bharatiya Janata Party         24     17348473
26                               Gujarat                           Indian National Congress          1       671883
27                               Haryana                             Bharatiya Janata Party          5      3467029
28                               Haryana                           Indian National Congress          5      3300164
29                      Himachal Pradesh                             Bharatiya Janata Party          4      2296631

In [129]:
# ============================================
# MODULE 40: STATE WINNING PARTY
# ============================================

state_winning_party = (
    state_results_2024
    .sort_values(
        ["state", "seats_won"],
        ascending=[True, False]
    )
    .groupby("state")
    .first()
    .reset_index()
)

state_winning_party = state_winning_party[
    [
        "state",
        "party",
        "seats_won"
    ]
]

state_winning_party = state_winning_party.rename(
    columns={
        "party": "leading_party",
        "seats_won": "leading_party_seats"
    }
)

display(state_winning_party)

                                   state                 leading_party  leading_party_seats
0              Andaman & Nicobar Islands        Bharatiya Janata Party                    1
1                         Andhra Pradesh                  Telugu Desam                   16
2                      Arunachal Pradesh        Bharatiya Janata Party                    2
3                                  Assam        Bharatiya Janata Party                    9
4                                  Bihar        Bharatiya Janata Party                   12
5                             Chandigarh      Indian National Congress                    1
6                           Chhattisgarh        Bharatiya Janata Party                   10
7   Dadra & Nagar Haveli and Daman & Diu        Bharatiya Janata Party                    1
8                                    Goa        Bharatiya Janata Party                    1
9                                Gujarat        Bharatiya Janata Party                   24
10                               Haryana        Bharatiya Janata Party                    5
11                      Himachal Pradesh        Bharatiya Janata Party                    4
12                     Jammu and Kashmir        Bharatiya Janata Party                    2
13                             Jharkhand        Bharatiya Janata Party                    8
14                             Karnataka        Bharatiya Janata Party                   17
15                                Kerala      Indian National Congress                   14
16                                Ladakh                   Independent                    1
17                           Lakshadweep      Indian National Congress                    1
18                        Madhya Pradesh        Bharatiya Janata Party                   29
19                           Maharashtra      Indian National Congress                   13
20                               Manipur      Indian National Congress                    2
21                             Meghalaya      Indian National Congress                    1
22                               Mizoram       Zoram People’s Movement                    1
23                          NCT OF Delhi        Bharatiya Janata Party                    7
24                              Nagaland      Indian National Congress                    1
25                                Odisha        Bharatiya Janata Party                   20
26                            Puducherry      Indian National Congress                    1
27                                Punjab      Indian National Congress                    7
28                             Rajasthan        Bharatiya Janata Party                   14
29                                Sikkim      Sikkim Krantikari Morcha                    1
30                            Tamil Nadu     Dravida Munnetra Kazhagam                   22
31                             Telangana        Bharatiya Janata Party                    8
32                               Tripura        Bharatiya Janata Party                    2
33                         Uttar Pradesh               Samajwadi Party                   37
34                           Uttarakhand        Bharatiya Janata Party                    5
35                           West Bengal  All India Trinamool Congress                   29

In [130]:
# ============================================
# MODULE 41: NATIONAL ELECTION SUMMARY
# ============================================

total_constituencies = (
    constituency_results_2024["pc_name"].nunique()
)

total_parties = (
    constituency_results_2024["party"].nunique()
)

total_votes = (
    vote_analysis["total_votes"].sum()
)

total_candidates = (
    vote_analysis["candidate"].nunique()
)

print("============================================")
print("INDIA LOK SABHA ELECTION 2024")
print("============================================")

print("Total Constituencies :", total_constituencies)
print("Total Candidates     :", total_candidates)
print("Total Parties        :", total_parties)
print("Total Votes          :", total_votes)

print("\nTop Parties by Seats:")
display(national_party_results.head(10))

============================================
INDIA LOK SABHA ELECTION 2024
============================================
Total Constituencies : 540
Total Candidates     : 8101
Total Parties        : 42
Total Votes          : 645363445

Top Parties by Seats:

                                               party  seats_won
8                             Bharatiya Janata Party        239
15                          Indian National Congress         99
31                                   Samajwadi Party         37
4                       All India Trinamool Congress         29
12                         Dravida Munnetra Kazhagam         22
36                                      Telugu Desam         16
20                              Janata Dal  (United)         12
34             Shiv Sena (Uddhav Balasaheb Thackrey)          9
26  Nationalist Congress Party – Sharadchandra Pawar          8
14                                       Independent          7

In [131]:
# ============================================
# MODULE 42: STATE SEAT VALIDATION
# ============================================

state_seat_totals = (
    constituency_results_2024
    .groupby("state")
    .size()
    .reset_index(name="seats")
    .sort_values("seats", ascending=False)
)

display(state_seat_totals)

                                   state  seats
33                         Uttar Pradesh     80
19                           Maharashtra     48
35                           West Bengal     42
4                                  Bihar     40
30                            Tamil Nadu     39
18                        Madhya Pradesh     29
14                             Karnataka     28
1                         Andhra Pradesh     25
28                             Rajasthan     25
9                                Gujarat     25
25                                Odisha     21
15                                Kerala     20
31                             Telangana     17
13                             Jharkhand     14
3                                  Assam     14
27                                Punjab     13
6                           Chhattisgarh     11
10                               Haryana     10
23                          NCT OF Delhi      7
34                           Uttarakhand      5
12                     Jammu and Kashmir      5
11                      Himachal Pradesh      4
21                             Meghalaya      2
2                      Arunachal Pradesh      2
7   Dadra & Nagar Haveli and Daman & Diu      2
20                               Manipur      2
32                               Tripura      2
8                                    Goa      2
0              Andaman & Nicobar Islands      1
16                                Ladakh      1
5                             Chandigarh      1
17                           Lakshadweep      1
26                            Puducherry      1
24                              Nagaland      1
22                               Mizoram      1
29                                Sikkim      1

In [132]:
print(
    "Total seats across all states:",
    state_seat_totals["seats"].sum()
)

Total seats across all states: 542

In [133]:
# ============================================
# MODULE 43: EXPORT FINAL DATASETS
# ============================================

PROCESSED_DATA = Path("../data/processed")

PROCESSED_DATA.mkdir(
    parents=True,
    exist_ok=True
)

constituency_results_2024.to_csv(
    PROCESSED_DATA / "constituency_results_2024.csv",
    index=False
)

state_results_2024.to_csv(
    PROCESSED_DATA / "state_party_results_2024.csv",
    index=False
)

national_party_results.to_csv(
    PROCESSED_DATA / "national_party_results_2024.csv",
    index=False
)

state_winning_party.to_csv(
    PROCESSED_DATA / "state_winning_party_2024.csv",
    index=False
)

party_votes.to_csv(
    PROCESSED_DATA / "national_party_votes_2024.csv",
    index=False
)

print("All final 2024 datasets exported successfully.")

All final 2024 datasets exported successfully.

In [134]:
# ============================================
# MODULE 44: VERIFY PROCESSED FILES
# ============================================

print("Processed files:")

for file in PROCESSED_DATA.glob("*.csv"):
    print("→", file.name)

Processed files:
→ constituency_results_2024.csv
→ india_turnout_summary.csv
→ lok_sabha_2024_winners.csv
→ lok_sabha_clean.csv
→ national_party_results_2024.csv
→ national_party_votes_2024.csv
→ state_party_results_2024.csv
→ state_winning_party_2024.csv

In [135]:
# ============================================
# MODULE 45: INDIA VOTER TURNOUT COMPARISON
# ============================================

turnout_2019 = 67.40
turnout_2024 = 66.10

change = turnout_2024 - turnout_2019

print("============================================")
print("INDIA VOTER TURNOUT ANALYSIS")
print("============================================")

print(f"2019 Voter Turnout : {turnout_2019}%")
print(f"2024 Voter Turnout : {turnout_2024}%")
print(f"Change             : {change:.2f} percentage points")

if change > 0:
    print("Result             : Voter turnout increased")
elif change < 0:
    print("Result             : Voter turnout decreased")
else:
    print("Result             : Voter turnout remained unchanged")

============================================
INDIA VOTER TURNOUT ANALYSIS
============================================
2019 Voter Turnout : 67.4%
2024 Voter Turnout : 66.1%
Change             : -1.30 percentage points
Result             : Voter turnout decreased

In [136]:
# ============================================
# MODULE 46: TURNOUT SUMMARY
# ============================================

turnout_summary = pd.DataFrame({
    "election_year": [2019, 2024],
    "voter_turnout_percentage": [67.40, 66.10]
})

turnout_summary["change_from_previous"] = (
    turnout_summary["voter_turnout_percentage"].diff()
)

display(turnout_summary)

   election_year  voter_turnout_percentage  change_from_previous
0           2019                      67.4                   NaN
1           2024                      66.1                  -1.3

In [137]:
# ============================================
# MODULE 47: EXPORT TURNOUT SUMMARY
# ============================================

turnout_summary.to_csv(
    PROCESSED_DATA / "india_turnout_summary.csv",
    index=False
)

print("Turnout summary exported successfully.")

Turnout summary exported successfully.